### ISSUE TITLE
CustomSessionStorage failed to find sessions by shop. Error Details: findSessionsByShopCallback not defined.

### ISSUE THREAD

**Issue by dani-sanomads** [Shopify/shopify-app-template-node#1004]
# Issue summary
I'm using CustomSessionStorage with storeCallback, deleteCallback and loadCallback. I'm getting : CustomSessionStorage failed to find sessions by shop. Error Details: findSessionsByShopCallback not defined. I'm using postgres as a DB and server setup is in TS. I'm getting the session values in the DB but not sure about this error message.
<img width="865" alt="Screen Shot 2022-08-09 at 3 58 26 PM" src="https://user-images.githubusercontent.com/101345208/183632133-5b20e249-9c2f-4304-a79e-e078729a429b.png">

   Secondly, I'm also getting the error of cookies and I'm not getting the display of my app. I keeps on loading and then i get this message: 
<img width="930" alt="Screen Shot 2022-08-09 at 3 56 08 PM" src="https://user-images.githubusercontent.com/101345208/183631563-9f5a2312-3480-4112-9ab2-3372a4da7d82.png">

**Comment by dani-sanomads** [comment]
"vite-plugin-react can't detect preamble. Something is wrong." After defining the findSessionsByShopCallback(). I finally got this on the frontend console. Maybe something wrong with the session on the frontend or I'm missing something.

**Comment by dani-sanomads** [comment]
Instead of using the CustomSession Storage. I'm going to use the PostgresSessionStorage because it works fine with vitejs. Maybe we can close this issue or we can wait for CustomSessionStorage updates for findSessionsByShopCallback() docs. Thanks.

**Comment by JohnYacoub** [comment]
I am getting the same error after using Redis CustomSessionStorage, and I really don't want to change the DB currently

**Comment by dani-sanomads** [comment]
Yes, I tried but it wasn't working. Let us know if you find any solution regarding **findSessionsByShopCallback** . Thanks. @JohnYacoub

**Comment by jeff0723** [comment]
encounter this error `CustomSessionStorage failed to find sessions by shop. Error Details: findSessionsByShopCallback not defined. `while implementing mongodb too. 

I found that the `findSessionsByShopCallback` is optional in the [](https://github.com/Shopify/shopify-api-node/blob/main/docs/usage/customsessions.md).

How can we fix it or how can we implement mongodb in shopify app.

**Comment by alexandrosk** [comment]
Im going mental with this issue, i've done everything correctly and I still get this message :argh:

`findSessionsByShopCallback failed to find sessions by shop. Error Details: findSessionsByShopCallback not defined.`

Crazy part is that I defined this function and called in also on the CustomSessionStorage lol

**Comment by jeff0723** [comment]
just don't use CustomSessionStorage.

**Comment by alexandrosk** [comment]
@jeff0723 I was going crazy because I wanted to make it work with redis upstash, turns out if you use railway or any other redis with the RedisSession it just works lol -.-

**Comment by benkissi** [comment]
@alexandrosk the CustomSessionStorage constructor takes in the values at specific positions. `findSessionsByShopCallback` bind should be the last one in the instance call

```
...
SESSION_STORAGE: new Shopify.Session.CustomSessionStorage(
    sessionStorage.storeCallback.bind(sessionStorage),
    sessionStorage.loadCallback.bind(sessionStorage),
    sessionStorage.deleteCallback.bind(sessionStorage),
    sessionStorage.deleteSessionsCallback.bind(sessionStorage),
    sessionStorage.findSessionsByShopCallback.bind(sessionStorage)
  ),
  ...
  ```

then you can add the callbacks to the redis class like this
```
  async findSessionsByShopCallback(id) {
    try {
      let reply = await this.client.get(id);
      if (reply) {
        return [JSON.parse(reply)];
      } else {
        return [];
      }
    } catch (err) {
      throw new Error(err);
    }
  }

  async deleteSessionsCallback(ids) {
    try {
      let promises = [];
      ids.forEach((id) => {
        promises.push(this.client.del(id));
      });
      await Promise.all(promises);
      return true;
    } catch (error) {
      throw new Error(err);
    }
  }
```
