### ISSUE TITLE
App install flow break    

### ISSUE THREAD

**Issue by adventuretocode** [Shopify/shopify-app-template-node#1080]
# Issue summary

both URL wrong 
https://4fda-180-211-99-158.ngrok.io/?hmac=c097c3d31117fe45a2a445d8be4bf27e2c3da4548513f8289f382a3a59c04619&host=c3RhZ2luZy1jb252ZXJzaW9zLm15c2hvcGlmeS5jb20vYWRtaW4&shop=staging-conversios.myshopify.com&timestamp=1664444520

https://qa-conversios.myshopify.com/admin/apps/dbfa3d88cf635407319677513f4bea5e/?hmac=4a81d4a355fa4ccf2c86cf2bb4dc6ce02973fa14d22663e4384fea208b988037&host=cWEtY29udmVyc2lvcy5teXNob3BpZnkuY29tL2FkbWlu&shop=qa-conversios.myshopify.com&timestamp=1664444854

Write a short description of the issue here ↓
when i was try to install app few store app get redirected to the permission screen one store i app not goes to the app permission screens. i am not sure this was Error from App bridge or server side 

## Expected behavior
from partner dashboard to try to install app into development store app  work fine. 

What do you think should happen?
app installation goes to auth screen then permission,

## Actual behavior

What actually happens?
when i am try to install the app it was goes to ?hmac them it will redirected app page don't goes to app permission screen
 
Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. 1. 1. app and store both in development.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: Chrome
- Device: HP 
- Operating System: Ubuntu

**Comment by adventuretocode** [comment]
1 app was create with cli  node template 
2 app runing with ngrock proxy.
3 i did the app uninstalled but not getting fire app uninstalled webhook on server side.
i am not get any error on  terminal or browser console side.

**Comment by mkevinosullivan** [comment]
The issue title says "app install flow break" ... from the message above, you're indicating that you're not getting the app uninstall webhook message, which would indicate that the the uninstall flow is not working ... which is it?

Please confirm:
1. you created the app with CLI ... which version of CLI? 3? What command did you use?
2. how are you running the app ... with `yarn dev` or `npm run dev` or are you using a different command?
3. did the app install successfully?

**Comment by mkevinosullivan** [comment]
As mentioned [here](https://github.com/Shopify/shopify-app-template-node/issues/1103#issuecomment-1275159000) in this [issue](https://github.com/Shopify/shopify-app-template-node/issues/1103), it may be that you're not waiting long enough for the `APP_UNINSTALLED` webhook to be sent by Shopify. Depending on how busy the systems are, there may be a slight delay in the message being sent to your app.

**Comment by adventuretocode** [comment]
this happen with the ngrok may be shopify blocked this proxy. app working fine with my own domain and hosting.

**Comment by adventuretocode** [comment]
@fonya2014   my issue was ngrock proxy.  you can check console Error
