### ISSUE TITLE
MySQL Session Storage not initializing as expected

### ISSUE THREAD

**Issue by SilasGrygier** [Shopify/shopify-app-template-node#1082]
# Issue summary
I'm unable to initialize a MySQLSessionStorage instance for the shopify context of my App and I don't know if it's a bug or if I have missed some configuration details, any feedback is appreciated!

I installed a brand new template app and only changed the session_storage property as follows:
```
Shopify.Context.initialize({
  API_KEY: process.env.SHOPIFY_API_KEY,
  ...
  ...
  ...
  SESSION_STORAGE: Shopify.Session.MySQLSessionStorage.withCredentials(process.env.DBHOST, process.env.DBNAME, process.env.DBUSER, process.env.DBPASSWORD, {}),
});
```

After running the app (not installed yet) it crashes when trying to install it. My guess is that the MYSQLSessionStorage instance calls it's LoadOfflineSession(id) function before setting up the session DB table

## Expected behavior

In an older version of the template, the MYSQLSessionStorage instance was initalized succesfully, and automatically setup a db table called **shopify_sessions** prioer to the installation process taking place which also succesfully stored the offline/online access tokens after completing the Installation/OAuth process.

## Actual behavior
I receive the following error message after running the app in development mode using `npm run dev` and trying to click the install link 

```
 C:\shopify\sales-counter-v2\web\node_modules\mysql2\promise.js:93
backend  |     const localErr = new Error();
backend  |                      ^
backend  | 
backend  | Error: Table 'test.shopify_sessions' doesn't exist
backend  |     at PromiseConnection.query (C:\shopify\sales-counter-v2\web\node_modules\mysql2\promise.js:93:22)
backend  |     at MySQLSessionStorage.query (C:\shopify\sales-counter-v2\web\node_modules\@shopify\shopify-api\dist\auth\session\storage\mysql.js:201:32)
backend  |     at MySQLSessionStorage.<anonymous> (C:\shopify\sales-counter-v2\web\node_modules\@shopify\shopify-api\dist\auth\session\storage\mysql.js:60:51)
backend  |     at step (C:shopify\sales-counter-v2\web\node_modules\tslib\tslib.js:144:27)
backend  |     at Object.next (C:\shopify\sales-counter-v2\web\node_modules\tslib\tslib.js:125:57)
backend  |     at fulfilled (C:\shopify\sales-counter-v2\web\node_modules\tslib\tslib.js:115:62)
backend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
backend  |   code: 'ER_NO_SUCH_TABLE',
backend  |   errno: 1146,
backend  |   sql: '\n' +
backend  |     '      SELECT * FROM `shopify_sessions`\n' +
backend  |     "      WHERE id = 'myDevStore.myshopify.com';\n" +
backend  |     '    ',
backend  |   sqlState: '42S02',
backend  |   sqlMessage: "Table 'appDB.shopify_sessions' doesn't exist"
backend  | }
backend  |
backend  | Node.js v18.4.0

```

## Steps to reproduce the problem

1. Setup a DB to allow the Shopify.Session.MySQLSessionStorage instance to connect to it ( I used a xampp server that locally hosts a database called appDB)

2. Create a node template app using the shopify cli by typing `npm init @shopify/app@latest` into your terminal if you use npm as your package manager otherwise `yarn create @shopify/app` for yarn or `pnpm create @shopify/app` for pnpm
 
3. Change the Shopify.Context.Initialize parameters in the **web/index.js** file to the following:
```
Shopify.Context.initialize({
  API_KEY: process.env.SHOPIFY_API_KEY,
  API_SECRET_KEY: process.env.SHOPIFY_API_SECRET,
  SCOPES: process.env.SCOPES.split(","),
  HOST_NAME: process.env.HOST.replace(/https?:\/\//, ""),
  HOST_SCHEME: process.env.HOST.split("://")[0],
  API_VERSION: LATEST_API_VERSION,
  IS_EMBEDDED_APP: true,
  SESSION_STORAGE: Shopify.Session.MySQLSessionStorage.withCredentials(process.env.DBHOST, process.env.DBNAME, process.env.DBUSER, process.env.DBPASSWORD, {}),
});
```

4. Run `npm run dev`

5. Click the installation url that's being output in the terminal once the app is up and running

## Reduced test case
I've also tried to manually setup a db table called shopify_sessions in which case I get a `ER_TABLE_EXISTS_ERROR` after running the app. In this case it seems like the app now tries to run the CreateTable() function of the MYSQL file that's located at web\node_modules\@shopify\shopify-api\dist\auth\session\storage\mysql.js of the relative path of any node template app

## Specifications

- Browser: Chrome
- Device: Laptop 
- Operating System: Windows 10

**Comment by Michael-Gibbons** [comment]
@SilasGrygier I believe your configuration is correct if that function had a `withCredentials` function. You can see [here](https://github.com/Shopify/shopify-api-node/blob/main/src/auth/session/storage/sqlite.ts) that there currently is no support to pass in credentials. This is likely a bug

**Comment by james-theinsightlab** [comment]
It might be related, but I found I was getting that error message too when I had multiple databases on the one MySQL instance, either for different apps with a database each, or in my case when I had multiple databases to support different developers working on different branches.

See https://github.com/Shopify/shopify-api-js/issues/585 where the problem was fixed in a newer version recently.

**Comment by cquemin** [comment]
@SilasGrygier Would you mind trying with the new v6 of [shopify-api](https://github.com/Shopify/shopify-api-js) and the new 'independent' [session storage implementations](https://github.com/Shopify/shopify-app-js/tree/main/packages)? I believe it might be related to issue @james-theinsightlab mentioned where I fixed a bug where we were not being database specific when looking at creating the session tables. 

You can find [a migration guide from v5 to v6 here](https://github.com/Shopify/shopify-api-js/blob/main/docs/migrating-to-v6.md).
Let me know if that fixes the issue for you.
