### ISSUE TITLE
Empty Folder While Creating New Theme App Extension

### ISSUE THREAD

**Issue by muhammad-hunnain786** [Shopify/shopify-app-template-node#1087]
# Issue summary

iam creating a theme app extension using command

npm run shopify app generate extension

it just create a folder in extensions folder which is empty

it doesnt contain the files of extension

## Expected behavior

it should contain the files of a extension so i can build and deploy the extension

## Actual behavior

it doesnt contain the files of extension

## Steps to reproduce the problem

1. npm run shopify app generate extension
2. select theme app extension
3. enter name for the extension
4. it create the empty extension folder

## Specifications

- Browser: google chrome
- Device: dell
- Operating System: windows 11

**Comment by mkevinosullivan** [comment]
This issue should be reported in the [CLI](https://github.com/Shopify/cli) repository, not this one.
