### ISSUE TITLE
returnUrl in app subscription not working

### ISSUE THREAD

**Issue by mahamudml** [Shopify/shopify-app-template-node#1100]
# Issue summary
Added returnUrl, but it is not working: https://github.com/Shopify/shopify-app-template-node/blob/6eb5e06d124d9f6f2ded3d02b2e072e4dd50578c/web/helpers/ensure-billing.js#L112

## Expected behavior

After billing the user should be redirected to returlUrl.

## Actual behavior

After billing the user is redirected to home page of app, it is not redirected to returnUrl

## Specifications

- Browser: Chrome
- Device: Macbook
- Operating System: MacOS

**Comment by mkevinosullivan** [comment]
To what value are you setting `returnUrl`?
