### ISSUE TITLE
When app is uninstalled, it is not possible to reinstall it again

### ISSUE THREAD

**Issue by fonya2014** [Shopify/shopify-app-template-node#1103]
When I uninstall the app, and after that install it again, it shows the "Nothing Found" screen.

This is probably happening because the shop can't be deleted here in index.js:

`Shopify.Webhooks.Registry.addHandler("APP_UNINSTALLED", {
  path: "/api/webhooks",
  webhookHandler: async (_topic, shop, _body) => {
    await AppInstallations.delete(shop);
  },
});`

AppInstallations function uses a session to get access to the shopDomain.
But the session can't be accessed in the APP_UNINSTALLED hook, because the session is cleared earlier than the APP_UNINSTALLED is fired.

**Comment by mkevinosullivan** [comment]
That thread is related to accessing data on the Shopify system after an app has been deleted.

`AppInstallations` in the template is local to the app - all it is doing is deleting the session(s) related to that shop in the apps local session storage.

When you setup the `Shopify.Context`, what session storage are you using?

https://github.com/Shopify/shopify-app-template-node/blob/cli_three/web/index.js#L26-L35

**Comment by mkevinosullivan** [comment]
That is correct.  Do you know for certain that the `APP_UNINSTALLED` webhook has been received by the app before the re-installation is attempted?  There can be a time delay between deleting the app in the UI and webhook being received.

**Comment by AkashM-eng** [comment]
I am also Facing same Issue [screencast](https://shopify.click/26850-65843-84628-6900-48930.webm).  finding a solution.

**Comment by mkevinosullivan** [comment]
No problem, happy to help!

**Comment by AkashM-eng** [comment]
> I tried to wait for a little before the second installation and it seems that everything works fine. Kevin, thank you so much for the clarification, and sorry for bothering you!

How much time have to wait for second time installation

**Comment by Lancer92** [comment]
looks like review process fails because not waiting for this 30-60 seconds for a webhook

**Comment by Lancer92** [comment]
@paulomarg @JaKXz @tylerball @mllemango @surma @mkevinosullivan 

How unprofessional, Shopify. First, you made such a serious bug in the recommended template and untested case. And now they just closed the issue without fixing it.

Merchants will not know that the application can only be reinstalled after 30-60 seconds. And surely someone will have such a problem.

This is against your own rules:
https://shopify.dev/apps/store/requirements#a-authentication
"When a merchant clicks Add App from your app's listing, your app must immediately authenticate using OAuth before any other steps occur, even if the merchant has previously installed and then uninstalled your app."

https://shopify.dev/apps/store/requirements#a-user-interface
Your app must have a user interface, including buttons, controls, setup or onboarding instructions, and features for merchants to interact with.

But on screen "There's no page at this address" there no user interface, buttons, controls, setup or onboarding instructions, and features for merchants to interact with.

related issue
https://github.com/Shopify/shopify-app-template-node/issues/1154

rejection messages
1. **App must set security headers to protect against clickjacking.** There was an error installing your app. The app must be installed to perform the security check. We expected OAuth to be initiated at `https://app-security.myshopify.com/admin/oauth/authorize` but were redirected to `https://app-security.myshopify.com/admin/apps/91de381d8d5a53699d605afd00295a1f/`. Your app must request installation immediately after clicking "add app." Apps must request shop access during installation, or reinstallation if the app was previously uninstalled from the shop. Learn more about authentication in our developer documentation

2. **App must verify the authenticity of the request from Shopify.** There was an error installing your app. The app must be installed to perform the security check. We expected OAuth to be initiated at `https://app-security.myshopify.com/admin/oauth/authorize` but were redirected to `https://app-security.myshopify.com/admin/apps/91de381d8d5a53699d605afd00295a1f/`. Your app must request installation immediately after clicking "add app." Apps must request shop access during installation, or reinstallation if the app was previously uninstalled from the shop. Learn more about authentication in our developer documentation

**Comment by Sky-bits** [comment]
> If the `APP_UNINSTALLED` webhook hasn't yet been received, and installation is triggered again, the app still thinks it's installed on the store (via the `AppInstallations` component, [this line](https://github.com/Shopify/shopify-app-template-node/blob/cli_three/web/index.js#L174)), and attempts to render `https://store-name.myshopify.com/admin/app/<app api key>` ([here](https://github.com/Shopify/shopify-app-template-node/blob/cli_three/web/index.js#L180-L184))
> 
> If using the template as is, you should see
> 
> ```
> backend  | Webhook processed, returned status code 200
> ```
> 
> appear in the window to indicate that a webhook has been received.




```
const appUninstallHandler = async (topic, shop, webhookRequestBody) => {  
  await SessionModel.deleteMany({ shop });
  res.status(200).send();
};

export default appUninstallHandler;

```

@mkevinosullivan  and @fonya2014   this code correct for the Express js side ?

**Comment by urimerhav** [comment]
Shocked this hasn't been resolved yet. I got my app rejected by the review process about half a year ago and had to hack around to fix it. It's bizarre that Shopify's template app fails their own review process.

**Comment by fonya2014** [comment]
Hello @urimerhav ! That's great that you've been able to solve the issue! Could you please share your solution?
Thank you!

**Comment by urimerhav** [comment]
@fonya2014 I'm afraid this information is lost to the depths of my poor memory and time. I vaguely remember something lie redirecting to app install on authentication failure. But I really don't remember at all what the issue was and how I fixed it - only that the code assumes that processing the uninstall hook is good enough, when in practice the uninstall hook fires after an indeterminate, often long period of time.
