### ISSUE TITLE
Migrating this template to v3, vite hot reload not working with nodemon.

### ISSUE THREAD

**Issue by Michael-Gibbons** [Shopify/shopify-app-template-node#1117]
# Issue summary
![image](https://user-images.githubusercontent.com/13829417/195492607-3a648889-980d-4250-80be-11dc658a18f0.png)

# Test code [here ](https://github.com/Michael-Gibbons/OSB/tree/v2) <-----

Vite is not playing nicely with nodemon most likely due to a lack of understanding on my part. When nodemon restarts the server, I expect hmr websockets to re-establish connection, instead an error that I am unable to get the stack trace of exits nodemon.

## Expected behavior

Make change to file watched by nodemon -> nodemon detects change -> server restart -> client loses connection to server -> few missed pings until server is back up -> connection re-established -> profit

## Actual behavior

Make change to file watched by nodemon -> nodemon detects change -> server restart -> client loses connection to server -> Connection is immediately refused

## Steps to reproduce the problem

1. `git clone --single-branch --branch v2 https://github.com/Michael-Gibbons/OSB.git`
2. Have local postgresql server running [download toolkit here](https://www.postgresql.org/download/)
3. create `.env` file following `.env.example` from the above repository
4. `npm run serve`
5. follow any prompts needed to install the app to your partner account
6. install the app
7. Go through oauth, verify you see the `vite connected` console log
8. Make a change to `server/index.js` while a browser tab has the app open (so socket is active)
9. verify connection is refused

## Video demonstrating the issue and other potentially useless information

https://www.loom.com/share/e7835555a889447b8067476c6d95e90d

## Specifications

- Browser: Chrome
- Operating System: Windows

**Comment by Michael-Gibbons** [comment]
Motivation for this bug bounty is to create v2 of my shopify app boiler OSB 

https://github.com/Michael-Gibbons/OSB

**Comment by Michael-Gibbons** [comment]
![image](https://user-images.githubusercontent.com/13829417/195734350-57b8135a-ced3-4811-a7e0-5e5709357d5e.png)
![image](https://user-images.githubusercontent.com/13829417/195734360-f102ae4e-ae4e-4772-a878-43c6e6659f0e.png)

**Comment by Michael-Gibbons** [comment]
Submitted bug report to the cli as well 

https://github.com/Shopify/cli/issues/630

**Comment by Michael-Gibbons** [comment]
Removing the bug bounty, that was against the rules and I did not know. The bug is still up for grabs though!

**Comment by paulomarg** [comment]
Hey @Michael-Gibbons! As you already found out, the CLI currently uses a reverse proxy to handle both extension and app websockets. The 'connection refused' error you're seeing, in my own experience, happened before the CLI was properly set up to handle HMR requests, as per the vite configs in the repo instructions you mentioned.

Based on your findings, it sounds like it's working properly when it first loads, so I'm assuming you're running at least v3.4.0 of the CLI, right?

In any case, it sounds like the CLI reverse proxy is dropping the connection with your app server when it restarts, which I don't see happening on the new template. That leads me to think that there is some different setup step we're missing here.

One thing we changed when migrating over to CLI 3 was to stop running vite on the server in [middleware mode](https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server) - we now leverage the CLI's ability to run multiple commands to run vite [as its own server](https://github.com/Shopify/shopify-frontend-template-react/blob/f720a83458f3e83db4f2b5e85644345fc658cd32/package.json#L7) ([config here](https://github.com/Shopify/shopify-frontend-template-react/blob/f720a83458f3e83db4f2b5e85644345fc658cd32/shopify.web.toml)).

I could be wrong, but I think vite will [use the existing server](https://vitejs.dev/config/server-options.html#server-hmr) for hot reloading when not running as its own server, which might help explain the connection difference.

Hope this helps!

**Comment by Michael-Gibbons** [comment]
@paulomarg Thanks for your response!

I am currently using version 3.17.0 of the shopify cli in this project.

I believe you are absolutely correct that separating the vite server from the dev server should fix the issue.

The only thing I am concerned about is the fact that the expected behavior shows when not using the cli and that may or may not indicate an issue with the cli (likely a windows specific issue, might be related to the import of `system.exec` from ruby?)

Because of that I am unsure where to leave this issue.
