### ISSUE TITLE
App template for Cloudflare Workers/Pages

### ISSUE THREAD

**Issue by richilton** [Shopify/shopify-app-template-node#1131]
With the forthcoming release of @shopify/shopify-api v6 and its [support for runtimes other than node](https://github.com/Shopify/shopify-api-node/blob/shopify_api_next/docs/migrating-to-v6.md), are there any plans to create an app template for Cloudflare Workers/Pages using the [cf-worker adaptor](https://github.com/Shopify/shopify-api-node/tree/shopify_api_next/adapters/cf-worker) and [KV session storage](https://github.com/Shopify/shopify-api-node/tree/shopify_api_next/session-storage#cloudflare-kv)?

**Comment by gil--** [comment]
@richilton Should be possible via Nextjs to deploy to Cloudflare Workers. I have an example of Nextjs + Upstash (Redis) https://github.com/Checkout-Blocks/Shopify-App-Examples/tree/main/checkout-to-draft-with-upstash-sessions/web

Should be easy to replace Upstash with KV for the sessionStorage given they're very similar models at least for session storage. And then durable objects for more complex data -  https://developers.cloudflare.com/workers/learning/using-durable-objects/

**Comment by cquemin** [comment]
As of v6 the full library is compatible with workers and we have put session storage interfaces and implementation in their own package. You can find them here in this [monorepo](https://github.com/Shopify/shopify-app-js/tree/main/packages). You can find there [an example of session storage implementation with KV](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-session-storage-kv) in there too.
