### ISSUE TITLE
Sequelize with Shopify-CLI (node-template)

### ISSUE THREAD

**Issue by mtahirofficial** [Shopify/shopify-app-template-node#1148]
# Issue summary

I am using the Shopify-CLI node template for developing my app and [Sequelize ](https://sequelize.org/) for database queries.  Sequelize is developed in [common-js modules](https://nodejs.org/api/modules.html#modules-commonjs-modules) which is not compatible with Shopify-CLI which is developed using [ES module](https://nodejs.org/api/esm.html#modules-ecmascript-modules).

## Expected behavior

In my opinion, both things should use the same module type or Shopify should provide some configuration that may enable us to use Sequelize with node-template.

## Actual behavior

I try to import Sequelize models for queries
`import models from "../models/index.js";`

 but it generates an error.
<details>SyntaxError: The requested module '../models/index.js' does not provide an export named 'default'</details>

## Reduced test case

I tried to change my Sequelize files to [ES module](https://nodejs.org/api/esm.html#modules-ecmascript-modules). but there is another issue that Sequelize uses [require ](https://nodejs.org/en/knowledge/getting-started/what-is-require) function in the middle of the file to add Sequelize models dynamically but if we convert it to [ES module](https://nodejs.org/api/esm.html#modules-ecmascript-modules) we can not import any module in the middle of file in a specific function's body.

### Please help me to solve this problem

Here is my Sequelize file on _line#25_ its requires models dynamically where we can not use **_import_** statement to import models dynamically.

![code](https://user-images.githubusercontent.com/30388791/199200524-e1191d0e-185b-44b5-8da0-f76f40e809e3.png)

**Comment by Michael-Gibbons** [comment]
@mtahirofficial This is a slightly tricky problem to solve, you can check out my boiler here to see how I went about it using Sequelize 

https://github.com/Michael-Gibbons/OSB/tree/main/db

However, I believe you should do yourself a favor and switch over to [Prisma](https://www.prisma.io/) as it is quickly becoming the industry standard.

**Comment by mtahirofficial** [comment]
@Michael-Gibbons Thank you very much for your help. My problem has been solved, I was looking for a solution to this problem for a long time. May Allah grant you success, Ameen.

May Allah grant you much success, Ameen. And I will definitely read [Prizma](https://www.prisma.io/) too، inshaa ALLAH.
