### ISSUE TITLE
Shopify app template in production, test charge sticks in redirection

### ISSUE THREAD

**Issue by fonya2014** [Shopify/shopify-app-template-node#1165]
# Issue summary

Hello!

I deployed the Shopify app template to the hosting without any changes, and I get the following problem:
When I try to approve a test charge, the app sticks in redirection:

https://get-great.site/wp-content/uploads/2022/11/test_charge_redirection.mp4

NODE_ENV is "production"
Hosting is Heroku
Billing interval is EVERY_30_DAYS
Billing test is set to true

App history:
![image](https://user-images.githubusercontent.com/64004218/201660503-7475b25c-f2e9-4d95-869a-48cb38f07766.png)

If NODE_ENV is "development", everything works fine.

Could you please let me know, how to solve this issue?

Thank you!

## Expected behavior

After clicking the charge button, the operation is successful and the application interface is loaded

## Actual behavior

the app sticks in redirection: https://get-great.site/wp-content/uploads/2022/11/test_charge_redirection.mp4

## Steps to reproduce the problem

Deploy the template to Heroku, 
set NODE_ENV to "production",
Billing interval is set to EVERY_30_DAYS,
Billing test is set to true,
try to install the app in the store

**Comment by mkevinosullivan** [comment]
Hi @fonya2014, does this still happen with the new template, which removes the `helpers/ensure-billing.js` file and makes use of the billing check/request functionality added to the `@shopify/shopify-api` library?

- [Guide](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/billing.md)
- [Reference](https://github.com/Shopify/shopify-api-js/tree/main/docs/reference/billing)

Note that the billing configuration is done via the `api` property of the configuration passed to `shopifyApp` when using the `@shopify/shopify-app-express` package (used by the latest template). ([Example](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-express/docs/reference/shopifyApp.md#example))

**Comment by fonya2014** [comment]
Hello @mkevinosullivan ! Thank you so much for your reply! No, this issue doesn't happen in the new template
