### ISSUE TITLE
Theme app Extension Issue with Latest Shopify Node Template

### ISSUE THREAD

**Issue by dani-sanomads** [Shopify/shopify-app-template-node#1184]
# Issue summary
Shopify Node App Template issue after generating the theme app extension.

Created a Shopify Node app with latest template. Tested it using the npm run dev. Everything was working fine. But after adding the theme app extension . I tried running the app again using npm run dev. but got multiple error regarding rub y and shopify-cli.

## Expected behavior
After generating the theme app extension the app should work as intended but it is crashing.
I'm not sure about the issue . It can either be shopify-cli or ruby issue or maybe I'm missing something.

## Actual behavior

<img width="899" alt="Screenshot 2022-12-06 at 2 42 42 AM" src="https://user-images.githubusercontent.com/101345208/205750631-645aedd7-edbe-4e72-a359-0e41af620293.png">
<img width="757" alt="Screenshot 2022-12-06 at 2 42 55 AM" src="https://user-images.githubusercontent.com/101345208/205750647-4ce76f2d-a00d-4f9a-9f85-7a46b46bca0b.png">
<img width="772" alt="Screenshot 2022-12-06 at 2 43 20 AM" src="https://user-images.githubusercontent.com/101345208/205750654-8fea3225-5367-4db8-8ef5-eabe699d5cf3.png">
<img width="880" alt="Screenshot 2022-12-06 at 2 43 28 AM" src="https://user-images.githubusercontent.com/101345208/205750663-25c43697-f099-4ccd-8016-730a49fbecb2.png">

<details>
An error occurred while installing racc (1.6.1), and Bundler cannot continue.

In Gemfile:
  shopify-cli was resolved to 2.32.0, which depends on
    theme-check was resolved to 1.11.0, which depends on
      nokogiri was resolved to 1.13.9, which depends on
        racc
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using ast 2.4.2
Using bundler 2.3.26
Using liquid 5.4.0
Using rb-fsevent 0.11.2
Using concurrent-ruby 1.1.10
Using parser 3.1.3.0
Using bugsnag 6.25.0
Installing racc 1.6.1 with native extensions
Installing ffi 1.15.5 with native extensions

</details>
## Steps to reproduce the problem

1. npm init @shopify/app@latest
1. npm run shopify app generate extension
1. npm run dev

## Specifications

- Browser: Google Chrome
- Device: Mac Book Pro Intel
- Operating System: Ventura 13.0.1

**Comment by mkevinosullivan** [comment]
Hi @dani-sanomads, this appears to be similar/related to #1200.  It would likely be an issue with the CLI, as the CLI is attempting to build something... can you share the exact sequence of commands to reproduce this issue?

**Comment by dani-sanomads** [comment]
@mkevinosullivan These are the steps:
The template is v5 shopify/api it's not the latest one v6. But i tried to use theme app extension on 2-months and 3-months old node templates but i always get this error.

npm init @shopify/app@latest
npm run shopify app generate extension
npm run dev

**Comment by mkevinosullivan** [comment]
@dani-sanomads That looks like an error with the CLI itself ... the new CLI (v3) is written in JavaScript but it's using CLI v2 (which is written Ruby) to perform the theme-related stuff.  I would suggest posting the issue to https://github.com/Shopify/cli/issues instead.
