### ISSUE TITLE
Shopify CLI frontend build (node-template)

### ISSUE THREAD

**Issue by mtahirofficial** [Shopify/shopify-app-template-node#1186]
# Issue summary

I am trying to build the front end of the application developed using Shopify-CLI. I am trying to add `SHOPIFY_API_KEY` as explained [here](https://github.com/Shopify/shopify-app-template-node/tree/cli_three#build). 

I am trying this command `cd web/frontend/ && SHOPIFY_API_KEY=REPLACE_ME npm run build` from the root directory of my project. But,

`SHOPIFY_API_KEY` is not added through this command

## Expected behavior

As described [here](https://github.com/Shopify/shopify-app-template-node/tree/cli_three#build) the `SHOPIFY_API_KEY` should be added to the build.

## Actual behavior

When I run the command it's giving me an error described below and attached a screenshot of the error message.

<details>
`SHOPIFY_API_KEY` is not recognized as an internal or external command,
operable program, or batch file.
</details>

![Untitled](https://user-images.githubusercontent.com/30388791/205918451-53518db0-896d-439a-87de-cbfe37af24fb.png)

Please, anyone, help me with this problem. I will be grateful.

**Comment by fonya2014** [comment]
I don't remember for sure, as I can see it installed for root and /web for my project

**Comment by fonya2014** [comment]
try to install it globally 
`npm install --global cross-env`

**Comment by cquemin** [comment]
@mtahirofficial I noticed that you on windows. The instructions we put [there](https://github.com/Shopify/shopify-app-template-node/tree/cli_three#build) are for linux/MAC. That is a problem we should fix. Also, we should really adjust our frontend to use `cross-env` as we do from the backend.

I don't have a windows machine with me to test but here is what I would recommend to try:
Install `cross-env` as recommended by @fonya2014 with the following command : `npm install --global cross-env`
Try to enter the following commands one by one:
`cd web/frontend/`
`cross-env SHOPIFY_API_KEY=REPLACE_ME npm run build`

Hopefully this should help you.
