### ISSUE TITLE
Theme App Extension [ npm run dev ] | Shopify CLI : 3.25

### ISSUE THREAD

**Issue by dani-sanomads** [Shopify/shopify-app-template-node#1200]
<img width="892" alt="Screenshot 2022-12-13 at 2 16 12 AM" src="https://user-images.githubusercontent.com/101345208/207156453-797d6319-cf0a-464e-910a-57bd28e7662e.png">
<img width="959" alt="Screenshot 2022-12-13 at 2 21 23 AM" src="https://user-images.githubusercontent.com/101345208/207157203-bda8f7b6-e5f5-4031-a969-73974ba3fc2e.png">

- Bundler version : 2.3.26
- Ruby Version : ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-darwin22]
- Shopify CLI version: 3.25.0
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Ventura

**Comment by mkevinosullivan** [comment]
This does not appear to be related to this Node template ... if it's related to using the [Ruby template](https://github.com/Shopify/shopify-app-template-ruby), please open an issue in that repo.
