### ISSUE TITLE
Error on validateAuthenticatedSession

### ISSUE THREAD

**Issue by molotow11** [Shopify/shopify-app-template-node#1208]
# Issue summary

I have this error and app crashed when trying to access any route under /api

## Expected behavior

Some result output when accessing /api/*

## Actual behavior

2022-12-19 13:51:05 | backend  | [shopify-app/INFO] Running validateAuthenticatedSession
2022-12-19 13:51:05 | backend  | node_modules\@shopify\shopify-api\lib\auth\scopes\index.js:15
2022-12-19 13:51:05 | backend  |             .map(function (scope) { return scope.trim(); })
2022-12-19 13:51:05 | backend  |              ^
2022-12-19 13:51:05 | backend  |
2022-12-19 13:51:05 | backend  | TypeError: scopesArray.map is not a function
2022-12-19 13:51:05 | backend  |     at new AuthScopes (node_modules\@shopify\shopify-api\lib\auth\scopes\index.js:15:14)

## Steps to reproduce the problem

1. Start app with `yarn dev`
2. Try to access any route or just /api by the provided url

## Specifications

- Browser: Chrome
- Device: PC
- Operating System: Windows 11

**Comment by molotow11** [comment]
@mkevinosullivan please, could you help here?

**Comment by mkevinosullivan** [comment]
I've encountered this before when there may be multiple instances (of different versions) of the `@shopify/shopify-api` package in the `node_modules` directory.

Assuming you're on a Unix/Linux/MacOS machine, please run the following command in your app project's top directory and share the output please
```shell
find . -type d -name shopify-api
```

If on Windows, I think the following command should work
```shell
dir /s /b shopify-api
```

**Comment by Michael-Gibbons** [comment]
Great catch @mkevinosullivan

**Comment by mkevinosullivan** [comment]
@molotow11 Did you start your app using this template?

If so, then there should be no `@shopify/shopify-api` dependency in the top-level `package.json` (the dependencies therein should be primarily for the Shopify CLI).  All app related dependencies should be under `web`.

**Comment by molotow11** [comment]
@mkevinosullivan 
Thank you. Yes, it was this template used.

There is no `shopify-api` dependency.
Only this:
```
"dependencies": {
  "@shopify/app": "3.28.0",
  "@shopify/cli": "3.28.0",
},
```
Compared to current template package.json and it looks equal but different version.

**Comment by NomanHameed** [comment]
> Thanks @molotow11.
> 
> Since that is the case, please delete `node_modules\@shopify\shopify-api` (it shouldn't be there, don't know how/why it got installed there) and keep `web\node_modules\@shopify\shopify-api` and the behaviour should then be correct.
> 
> If after running the app `node_modules\@shopify\shopify-api` appears again, then examine the `package.json` files ... something somewhere is installing `shopify-api` in that location that shouldn't be ... this is not part of the standard template.

This is the best and accurate solution for this issue i'm also facing same issue with PostGreSQL

**Comment by danyn** [comment]
I had the same issue because of where I added the mongodb storage package from shopify.

if npm install @shopify/shopify-app-session-storage-mongodb in the top level it adds all its sub dependencies including @shopify/shopify-api so the duplication does happen because of this.

if you npm remove @shopify/shopify-app-session-storage-mongodb it will remove those subdepencies as well. 
So far that fixed it for me.

then npm install @shopify/shopify-app-session-storage-mongodb in the web folder. I think I meant to do that and just got clumsy in the terminal.  It is a shame that the package initially works and then starts throwing errors later on like the  one mentioned above.  That makes this thread useful if this is your case.

**Comment by talhajunaidd** [comment]
I was facing the similar issue with `shopify-app-session-storage-sqlite`  and replaced it with `shopify-app-session-storage-memory`

**Comment by mstindia-com** [comment]
I was facing the same issue. @mkevinosullivan is right. There should be only one **node_modules\@shopify\shopify-api**.
But, I think this is because of old shopify-app-express version (1.1.0). 
As pointed out by  @talhajunaidd  I updated @shopify/shopify-app-express in web/packages.json from ^1.1.0 to '^2.0.0' and it fixed.

**Comment by bjorndonald** [comment]
> Later I upgraded `@shopify/shopify-app-express` in `web/packages.json` from `^1.1.0` to '^2.0.0' . That fixed the issue with `shopify-app-session-storage-sqlite` as well.

Thank you for this. It worked for me

**Comment by saad3074** [comment]
> Later I upgraded `@shopify/shopify-app-express` in `web/packages.json` from `^1.1.0` to '^2.0.0' . That fixed the issue with `shopify-app-session-storage-sqlite` as well.

Thank you for this. It worked for me

**Comment by randomprogramming** [comment]
> Later I upgraded `@shopify/shopify-app-express` in `web/packages.json` from `^1.1.0` to '^2.0.0' . That fixed the issue with `shopify-app-session-storage-sqlite` as well.

Thanks, this worked, but I also had to update `@shopify/shopify-app-session-storage-sqlite` to `^1.2.1'

**Comment by esterified** [comment]
downgrading to `@shopify/shopify-app-session-storage-postgresql ^1.0.0` fixed the error for me 
cause already used version for sqlite is: `@shopify/shopify-app-session-storage-sqlite  ^1.0.0`
