### ISSUE TITLE
App is outdated with new admin routes

### ISSUE THREAD

**Issue by Michael-Gibbons** [Shopify/shopify-app-template-node#1223]
# Issue summary

The new admin routes are making an outdated app warning appear on development apps. This is either a bug in this template failing to cover certain security criteria or a bug in the shopify admin itself. 

- `@shopify/shopify-app-express` version: current
- Node version: v18.2.0
- Operating system: Windows

## Expected behavior

This error should not occur since:
- the security policy is set
- app bridge is up to date
- app bridge is initialized with HOST

[Here is the documentation for that](https://shopify.dev/apps/tools/app-bridge/updating-overview#ensure-compatibility-with-the-new-shopify-admin-domain)

## Actual behavior

The error occurs, for some reason it only happens on dev, when in production the error does not occur. 

I've tested this on:
- Locally hosted dev version of my template [OSB](https://github.com/Michael-Gibbons/OSB)
- Externally hosted prod version of my template [OSB](https://github.com/Michael-Gibbons/OSB)
- Locally hosted dev version of this boiler
- Externally hosted prod version of this boiler

![image](https://user-images.githubusercontent.com/13829417/212462879-639bae21-7e6f-4d82-abf9-d00c985690fb.png)

## Steps to reproduce the problem

1. Install the app
2. run dev

**Comment by arsamFarooq** [comment]
Facing same error on shopify version
 "@shopify/cli": "3.28.0"
