### ISSUE TITLE
Custom Session Storage

### ISSUE THREAD

**Issue by muhammad-hunnain786** [Shopify/shopify-app-template-node#1226]
As Now The Shopify App Template Updated, I want to know how can i create custom session storage

its very clear that i cannot do it like old ways because now its not getting Shopify.Session.CustomSessionStorage

so i cannot use the below code

  sessionStorage: new Shopify.Session.CustomSessionStorage(
    storeCallback,
    loadCallback,
    deleteCallback
  ),
  
  
  can anyone help me in this ???

**Comment by mkevinosullivan** [comment]
See the [implementing session storage](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-session-storage/implementing-session-storage.md) guide.

Using the example in that guide, you would import your custom session storage (e.g., `CsvSessionStorage`) and attach it to your API configuration using
```
  sessionStorage: new CsvSessionStorage(),
```

**Comment by muhammad-hunnain786** [comment]
yeah i tried that 

but iam receiving an error on SessionStorage from @shopify/shopify-app-session-storage

i tried

import {SessionStorage} from '@shopify/shopify-app-session-storage';

and

import SessionStorage from '@shopify/shopify-app-session-storage';


one gives undefined and another gives empty object {}

can you help me in this ???

**Comment by muhammad-hunnain786** [comment]
yes 

i have installed that package

iam working on latest app template which is on @shopify/shopify-app-express version 1.1.0
and
the version of @shopify/shopify-app-session-storage is 1.0.2

**Comment by mkevinosullivan** [comment]
The correct `import` statement is
```js
import {SessionStorage} from '@shopify/shopify-app-session-storage';
```

What's the exact error you are receiving?

**Comment by meandillar** [comment]
@fotimo @muhammad-hunnain786 

I was also struggling with how to implement CustomSessionStorage. I adapted the [guide](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-session-storage/implementing-session-storage.md) that @mkevinosullivan linked to. If you're not using typescript you don't need to use the `implements` keyword, and you also don't need to `extend` the `SessionStorage` class from Shopify. Simply define your class and it's methods - something like:

```
export class CustomSessionStorage {
  async storeSession(session) {...}

  async loadSession(id) {...}

  async deleteSession(id) {...}

  async deleteSessions(ids) {...}

  async findSessionsByShop(shop) {...}
}
```

The shopify guide linked to above gives all the return values needed for the class methods. Create an instance when you initialise your shopify config like:

`sessionStorage: new CustomSessionStorage()`

**Comment by mkevinosullivan** [comment]
@meandillar Thanks for your reply - yes, the guide is in TypeScript and needs to be converted to JavaScript for JS-based applications.

**Comment by joantune** [comment]
orrr - @mkevinosullivan - do a template in Typescript:)

Also - if the shopify store domain is already on the JWT token - why do we need to store sessions at all?:)

can't we just validate the token and use that? that would be sooo much better and leaner - and everything:)

**Comment by pkyek1** [comment]
that means that we cant use import {SessionStorage} from '@shopify/shopify-app-session-storage'; in JS based projects because its in type script

thats bad

because when we implement custom session like this

export class CustomSessionStorage {
  async storeSession(session) {...}

  async loadSession(id) {...}

  async deleteSession(id) {...}

  async deleteSessions(ids) {...}

  async findSessionsByShop(shop) {...}
}

it does not have isActive function there 


espacially its required in the new shopify app remix template

**Comment by meandillar** [comment]
@pkyek1 if you create a custom implementation there is nothing stopping you from adding an "isActive" function, or any other function for that matter

**Comment by HxshPatil** [comment]
> [@meandillar](https://github.com/meandillar) Thanks for your reply - yes, the guide is in TypeScript and needs to be converted to JavaScript for JS-based applications.

hi! i am unable to find the guide mentioned above

**Comment by HxshPatil** [comment]
> See the [implementing session storage](https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-session-storage/implementing-session-storage.md) guide.
> 
> Using the example in that guide, you would import your custom session storage (e.g., `CsvSessionStorage`) and attach it to your API configuration using
> 
> ```
>   sessionStorage: new CsvSessionStorage(),
> ```

Hi! unable to find the guide. Could you reshare the updated link?
