### ISSUE TITLE
Redirecting back to app after billing / how to get app name 

### ISSUE THREAD

**Issue by JeaneC** [Shopify/shopify-app-template-node#1227]
I'm using `appSubscriptionCreate` to create a subscription which needs a `returnUrl` and according to shopify support this returnUrl needs to be back in my embedded app. Would be nice if this could be automatic (the user just returns back to the page they were at before billing).

I don't know how to get a return URL in the backend of the embedded app. I saw a function called `getEmbeddedAppUrl` somewhere, but this only seems to work well during the auth flow (where it's used) where the host and shop name are passed as query parameters.

I also thought about manually constructing the URL `www.store.myshopify.com/admin/${APP_NAME}`, but then I need an app name

**Comment by juanpasolano** [comment]
@mkevinosullivan, the guides appear to be out of date. I am wondering if there is no easier way to get the store and host, it seems they are used internally to check auth but not exposed anywhere in the shopify-api-js api.
Is there a reason why getting this apparently basic information is not easily accessible?
