### ISSUE TITLE
TailwinCss does not work when installed into the project

### ISSUE THREAD

**Issue by Trinh-Viet-Dat** [Shopify/shopify-app-template-node#1324]
Hello developer, I can't use tailwinCss in my project. Do you have any way to fix that?

**Comment by paulomarg** [comment]
Hi, sorry to hear you're having problems. Unfortunately, we only provide support for issues in our own packages in this repo. If you can narrow the problem down to something provided in this template, we'll be happy to fix it, but unfortunately, without details there's not a lot we can do.

It's possible that others have already gone through this problem in the past, so I'd recommend you look in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) to see if anyone else has had problems.

**Comment by wellenzhong** [comment]
Maybe you need to add these lines
```@tailwind base;
@tailwind components;
@tailwind utilities;
``` to your frontend css file.
