### ISSUE TITLE
Error when confirming a payment in the Shopify API.

### ISSUE THREAD

**Issue by Thiago-Mota-Santos** [Shopify/shopify-app-template-node#1346]
I am encountering the following error:

```sh
{
	"data": {
		"paymentSessionResolve": {
			"paymentSession": null,
			"userErrors": [
				{
					"field": [
						"id"
					],
					"message": "Payment session has already been resolved with a different authentication, has already been rejected, or the response to start_payment_session request has not been received."
				}
			]
		}
	},
	"extensions": {
		"cost": {
			"requestedQueryCost": 13,
			"actualQueryCost": 10,
			"throttleStatus": {
				"maximumAvailable": 1092000.0,
				"currentlyAvailable": 1091990,
				"restoreRate": 54600.0
			}
		}
	}
}
```

I saw that it could involve an issue with online and offline tokens, but I have already validated that my application tokens are offline:

```sh
 "isOnline": false,
````

The next thing I’m investigating is the `paymentSession`

What should I do in these cases? Any suggestions on how to proceed?

**Comment by lizkenyon** [comment]
Hi there 👋 

This seems like this is an issue with the Shopify API, and not the Node app template.

Could you please create a discussion in the [developer community forums](https://community.shopify.dev/c/graphql-troubleshooting/8)? This should get routed to the correct produc teams.
