### ISSUE TITLE
Apollo Client

### ISSUE THREAD

**Issue by cdedreuille** [Shopify/shopify-app-template-node#555]
I just started on a new app for Shopify and as I'm new to Apollo I was really surprise to see that react-apollo is not really supported. Apollo is asking to use @apollo-client instead.

Is this something you are planning to update?

**Comment by zinyosrim** [comment]
I have the same issue

**Comment by cdedreuille** [comment]
Hi, @paulomarg 👋 Any update on this one?

**Comment by milancermak** [comment]
I was experimenting with using `@apollo/client` as well. This works for me:

```javascript

// _app.js

import { ApolloClient, ApolloProvider, InMemoryCache, createHttpLink } from '@apollo/client';

//...

function MyProvider(props) {
  const app = useAppBridge();

  const client = new ApolloClient({
    cache: new InMemoryCache(),
    link: new createHttpLink({
      credentials: 'include',
      headers: {
        "Content-Type": "application/graphql"
      },
      fetch: authenticatedFetch(app)
    })
  });

  const Component = props.Component;

  return (
    <ApolloProvider client={client}>
      <Component {...props} />
    </ApolloProvider>
  );
}
```

And using `useQuery` in a component:


```tsx
import { gql, useQuery } from '@apollo/client';

const GET_SHOP_NAME = gql`
query {
  shop {
    id
    name
    email
  }
}
`

export default function ShopInfo() {
  const { loading, error, data } = useQuery(GET_SHOP_NAME);

  if (loading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>
  console.log(data)
  return (
      <p>OK</p>
  );
}
```

**Comment by zinyosrim** [comment]
@milancermak 

> I was experimenting with using `@apollo/client` as well. This works for me:
> 
> ```js
> // _app.js
> 
> import { ApolloClient, ApolloProvider, InMemoryCache, createHttpLink } from '@apollo/client';
> 
> //...
> 
> function MyProvider(props) {
>   const app = useAppBridge();
> 
>   const client = new ApolloClient({
>     cache: new InMemoryCache(),
>     link: createHttpLink({
>       credentials: 'include',
>       headers: {
>         "Content-Type": "application/graphql"
>       },
>       fetch: authenticatedFetch(app)
>     })
>   });
> 
>   const Component = props.Component;
> 
>   return (
>     <ApolloProvider client={client}>
>       <Component {...props} />
>     </ApolloProvider>
>   );
> }
> ```
> 
> And using `useQuery` in a component:
> 
> ```tsx
> import { gql, useQuery } from '@apollo/client';
> 
> const GET_SHOP_NAME = gql`
> query {
>   shop {
>     id
>     name
>     email
>   }
> }
> `
> 
> export default function ShopInfo() {
>   const { loading, error, data } = useQuery(GET_SHOP_NAME);
> 
>   if (loading) return <div>Loading...</div>;
>   if (error) return <div>{error.message}</div>
>   console.log(data)
>   return (
>       <p>OK</p>
>   );
> }
> ```

works fine

**Comment by jhldreams** [comment]
@milancermak  Hi, I also use new Apollo/Client, but when do a query throw useQuery , the graphql post request occured cros error. I see your code in new ApolloClient ,you ad a authenticatedFetch, Does this line must be included ?

**Comment by jhldreams** [comment]
any update of this issue ?? @paulomarg  i'm new to shopify app dev, find the react-apollo has been deprecated. I try to change it to Apollo/Client, but face query request keep loading , no error and no data return .

**Comment by zinyosrim** [comment]
The [code](https://github.com/Shopify/shopify-app-node/issues/555#issuecomment-798973158) of @milancermak worked fine for me

**Comment by jhldreams** [comment]
> The [code](https://github.com/Shopify/shopify-app-node/issues/555#issuecomment-798973158) of @milancermak worked fine for me

thanks

**Comment by hakimmazouz** [comment]
I keep getting this error even while using the code provided by @milancermak 

```Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.```
