### ISSUE TITLE
Enable cookies popup 

### ISSUE THREAD

**Issue by nikwebinopoly** [Shopify/shopify-app-template-node#616]
# Issue summary

I'm build app using this new API but still getting `Enable cookies popup`  error whenever app make auth call and reload whole app;  I've checked so many times official doc and code but not able to find any trace at my end. Even if I'm hitting **Enable cookies** button then also it's keep asking whenever it's make auth call and reload whole app. 

Then weird part is that it's appear for few time when whole app get reload then it's disappear and app start to behave normally.

![image](https://user-images.githubusercontent.com/63783615/114905537-af376d80-9e36-11eb-8fad-0ae17e18e394.png)

## Expected behavior

It should not ask every time at least once we hit **Enable cookie** button. 

## Actual behavior

What actually happens?

**P.S: Every time I restarting my node server it's asking same as well** 

Please check this video which I recorded with voice  [Enable cookie popup issue video](https://nimb.ws/SxLZUt)

## Steps to reproduce the problem

1. 1. 1. I have simply followed steps what we have on official documents like [Build a Shopify App with Node and React](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react and) & [Shopify App CLI](https://shopify.dev/tools/cli)

## Specifications

- Browser: Chrome 89.0.4389.114 (Official Build) (64-bit)
- Device: Desktop
- Operating System: 
  **Edition** `Windows 10 Pro`
  **Version** `20H2`
  **OS build** `19042.867`
  **Experience** `Windows Feature Experience Pack 120.2212.551.0`

**Comment by kasrakhosravi** [comment]
Same issue for me happens

**Comment by nikwebinopoly** [comment]
@kasrakhosravi  the link you shared as known issue it's explain about safari but I'm getting this issue in chrome, windows as well and also I'm using `@shopify/koa-shopify-auth": "^4.1.2`

**Comment by kasrakhosravi** [comment]
The issue started with safari, but now it has reached other browsers as well. They mention that in the final pages of the thread if you keep reading.

I think the solution for this would be to use this approach: https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens

**Comment by kasrakhosravi** [comment]
I think as more and more browsers are Blocking third-party cookies, solving this problem using the session tokens is a very clean and stable solution. I got it working on my app.

The link I posted above mainly focuses on ruby on rails; so I found this article really useful in solving the problem: https://blog.mixlogue.jp/posts/2020/20201209141909/

But in short, I persist the accessToken in my Postgress DB rather than relying on cookies. And that change requires several changes in `server.js` as well as `app.js`

**Comment by nikwebinopoly** [comment]
@kasrakhosravi  I've created my custom app skeleton from official Shopify CLI in which primary level operations come as written already so if you go here https://github.com/Shopify/shopify-app-node/blob/master/server/server.js this is how exact my code is lookalike because I'm using it's clone. I've checked your thread as where in which you are using `koa-shopify-auth-cookiless` but it should come with shopify's `koa-shopify-auth` as I think of it; I don't know more on it yet but the link you shared of shopify tutorial in that they mentioned if you're using shopify ruby or node api then middleware and other utilities  for decoding session tokens coming in built and I'm facing issue with that in built functions.

**Comment by kasrakhosravi** [comment]
> Having the same issue at the moment, if anyone has a code sample of the cookiless from it would be amazing to take a look

https://github.com/taketsu/shopify-demo-app-node-react

**Comment by cboiangiu** [comment]
> Having the same issue at the moment, if anyone has a code sample of the cookiless from it would be amazing to take a look

Here is a more up to date sample that I've tried to put up.

**Comment by smamessier** [comment]
Did anyone find a solution for this?

**Comment by nikwebinopoly** [comment]
@smamessier unfortunately not yet...!!

**Comment by ismailalabou** [comment]
> @nikwebinopoly I ended up switching to https://github.com/TheSecurityDev/simple-koa-shopify-auth which was mentioned in another post. it now works like a charm. Just had to manually create the host hash like
> 
> ```
>    server.use(
>           createShopifyAuth({
>               accessMode: "online",
>               authPath: "/auth",
>               async afterAuth(ctx) {
>                   const { shop, scope } = ctx.state.shopify;
>                   console.log(ctx.state.shopify);
>                   ACTIVE_SHOPIFY_SHOPS[shop] = scope;
>                   const host = Buffer.from(shop + "/admin").toString("base64");
>                   ctx.redirect(`/?shop=${shop}&host=${host}`);
>               },
>             })
>       );
> ```

hello @smamessier  mine have `prefix: "", instead of authPath: "/auth",`
any idea why ??
