### ISSUE TITLE
Expected a valid shop query parameter

### ISSUE THREAD

**Issue by aburak256** [Shopify/shopify-app-template-node#618]
I was trying to finish the tutorial with instructions. So after I redirect the user to the edit products page I am facing this error inside of admin UI. 

> Expected a valid shop query parameter

The main page of the app still works correctly.

## Specifications

- Browser: Chrome
- Operating System: Windows 10

**Comment by paulomarg** [comment]
Thanks for pointing this out @aburak256, you should be able to navigate properly if you [add a `ClientRouter` to your app](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-the-client-router), which is one of the next steps in that page.

We'll rearrange the steps so they don't lead to an error scenario.

**Comment by rodoneill** [comment]
This tripped me up as well...

The redirect using ?shop= should probably be mentioned earlier also - https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-shopify-app-bridge

**Comment by rahilwazir** [comment]
@paulomarg This appears to be ineffective. The app's initial page works fine, but when you navigate to the navigation link, it throws an error message saying "Expected a valid shop query parameter" in the app.

![image](https://user-images.githubusercontent.com/1818941/120039725-d335c380-c01e-11eb-81c5-3b0c1c8221c8.png)

Furthermore, even though I clicked on "Tab 2," the active navigation tab is still set to "Tab 1."

And I have added a `<ClientRouter /> component already.

![image](https://user-images.githubusercontent.com/1818941/120039903-17c15f00-c01f-11eb-8bee-f80406d07092.png)

**Comment by Theantipioneer** [comment]
> @paulomarg This appears to be ineffective. The app's initial page works fine, but when you navigate to the navigation link, it throws an error message saying "Expected a valid shop query parameter" in the app.
> 
> ![image](https://user-images.githubusercontent.com/1818941/120039725-d335c380-c01e-11eb-81c5-3b0c1c8221c8.png)
> 
> Furthermore, even though I clicked on "Tab 2," the active navigation tab is still set to "Tab 1."
> 
> And I have added a `<ClientRouter />` component already.
> 
> ![image](https://user-images.githubusercontent.com/1818941/120039903-17c15f00-c01f-11eb-8bee-f80406d07092.png)
> 
> This was no longer an issue with the cookie based approach described in the past examples.

Which is this cookie based approach you are referring to? Hopefully that can solve my problem.

**Comment by Theantipioneer** [comment]
@rahilwazir Which is this cookie based approach you are referring to? Hopefully that can solve my problem.

**Comment by Theantipioneer** [comment]
The tutorial is not updated and has been like this for a long while now.

**Comment by rahilwazir** [comment]
@Theantipioneer This is the PR https://github.com/Shopify/shopify-app-node/commit/442b3cd05012fe88f577e3901c7f4a310033d2ba that removed the Cookie implementation.
