### ISSUE TITLE
AppBridgeError INVALID_CONFIG: host must be provided

### ISSUE THREAD

**Issue by templatetuners** [Shopify/shopify-app-template-node#628]
When I open the app I get this error:

```
Unhandled Runtime Error
AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided
```

Sometimes I can't even install it because of this.

I have both **.env** and **process.env** files completed.
Sometimes I see for a second a message popup to enable cookies but I can't press Enable, the redirect is too fast.

**Comment by templatetuners** [comment]
https://github.com/Shopify/shopify-app-bridge/issues/48

**Comment by FiliSantillan** [comment]
The same thing happened to me, I added it by adding the `host` to the configuration.

A new query parameter named `host` has been introduced with the release of App Bridge 2.0. The base64-encoded host parameter represents the domain that is currently hosting your embedded app.


We start with the env file, it is important that you have the `SHOPIFY_APP_URL` defined, since it is the value that I use as `host`.

```
SHOPIFY_API_KEY=123
SHOPIFY_API_SECRET=shpss_123
SHOPIFY_API_SCOPES=read_products,write_products,read_script_tags,write_script_tags
SHOPIFY_APP_URL=https://123.ngrok.io
```

Now, in your `next.config.js` file you must take that value and send it, as well as the `apiKey`.

```javascript
// next.config.js

require("dotenv").config();
const webpack = require("webpack");

const apiKey = JSON.stringify(process.env.SHOPIFY_API_KEY);
const host = JSON.stringify(process.env.SHOPIFY_APP_URL);

module.exports = {
    webpack: (config) => {
        const env = { API_KEY: apiKey, HOST_URL: host };
        config.plugins.push(new webpack.DefinePlugin(env));
        return config;
    },
};

```

Finally you have to pass that `host` to the configuration. This must be modified with base64 and that's it. You can see your app from the store you are testing in.

```jsx
import React from "react";
import App from "next/app";
import Head from "next/head";
import { AppProvider } from "@shopify/polaris";
import { Provider } from "@shopify/app-bridge-react";
import "@shopify/polaris/dist/styles.css";
import translations from "@shopify/polaris/locales/es.json";

class MyApp extends App {
    render() {
        const { Component, pageProps, shopOrigin } = this.props;

        const config = {
            apiKey: API_KEY,
            shopOrigin,
            host: Buffer.from(HOST_URL).toString("base64"),
            forceRedirect: true,
        };

        return (
            <React.Fragment>
                <Head>
                    <title>Sample App</title>
                    <meta charSet="utf-8" />
                </Head>
                <Provider config={config}>
                    <AppProvider i18n={translations}>
                        <Component {...pageProps} />
                    </AppProvider>
                </Provider>
            </React.Fragment>
        );
    }
}

MyApp.getInitialProps = async ({ ctx }) => {
    return {
        shopOrigin: ctx.query.shop,
    };
};

export default MyApp;

```

**Comment by NoharaMasato** [comment]
> The same thing happened to me, I added it by adding the `host` to the configuration.
> 
> A new query parameter named `host` has been introduced with the release of App Bridge 2.0. The base64-encoded host parameter represents the domain that is currently hosting your embedded app.
> 
> We start with the env file, it is important that you have the `SHOPIFY_APP_URL` defined, since it is the value that I use as `host`.
> 
> ```
> SHOPIFY_API_KEY=123
> SHOPIFY_API_SECRET=shpss_123
> SHOPIFY_API_SCOPES=read_products,write_products,read_script_tags,write_script_tags
> SHOPIFY_APP_URL=https://123.ngrok.io
> ```
> 
> Now, in your `next.config.js` file you must take that value and send it, as well as the `apiKey`.
> 
> ```js
> // next.config.js
> 
> require("dotenv").config();
> const webpack = require("webpack");
> 
> const apiKey = JSON.stringify(process.env.SHOPIFY_API_KEY);
> const host = JSON.stringify(process.env.SHOPIFY_APP_URL);
> 
> module.exports = {
>     webpack: (config) => {
>         const env = { API_KEY: apiKey, HOST_URL: host };
>         config.plugins.push(new webpack.DefinePlugin(env));
>         return config;
>     },
> };
> ```
> 
> Finally you have to pass that `host` to the configuration. This must be modified with base64 and that's it. You can see your app from the store you are testing in.
> 
> ```js
> import React from "react";
> import App from "next/app";
> import Head from "next/head";
> import { AppProvider } from "@shopify/polaris";
> import { Provider } from "@shopify/app-bridge-react";
> import "@shopify/polaris/dist/styles.css";
> import translations from "@shopify/polaris/locales/es.json";
> 
> class MyApp extends App {
>     render() {
>         const { Component, pageProps, shopOrigin } = this.props;
> 
>         const config = {
>             apiKey: API_KEY,
>             shopOrigin,
>             host: Buffer.from(HOST_URL).toString("base64"),
>             forceRedirect: true,
>         };
> 
>         return (
>             <React.Fragment>
>                 <Head>
>                     <title>Sample App</title>
>                     <meta charSet="utf-8" />
>                 </Head>
>                 <Provider config={config}>
>                     <AppProvider i18n={translations}>
>                         <Component {...pageProps} />
>                     </AppProvider>
>                 </Provider>
>             </React.Fragment>
>         );
>     }
> }
> 
> MyApp.getInitialProps = async ({ ctx }) => {
>     return {
>         shopOrigin: ctx.query.shop,
>     };
> };
> 
> export default MyApp;
> ```

This works, Thanks.

**Comment by kinngh** [comment]
@FiliSantillan wait why are we pulling from `env` when it's available in the query?

Update your `pages/_app.js` to include `host` in `getInitialProps` and then call it in your `config` from `this.props` along side `shopOrigin`

```javascript
const { Component, pageProps, shopOrigin, host } = this.props;
const config = { apiKey: API_KEY, shopOrigin, host, forceRedirect: true };
...
...
...

MyApp.getInitialProps = async ({ ctx }) => {
  return { shopOrigin: ctx.query.shop, host: ctx.query.host };
};
```

And if you're using something like recurring subscriptions, you'll need to get host from the URL and pass it in your return URL

```javascript
const getHost = (ctx) => {
 const baseUrl = new URL(`https://${ctx.request.header.host}${ctx.request.url}`);
  return baseUrl.searchParams.get("host");  
 };
server.use(
 createShopifyAuth({ async afterAuth(ctx) {
  const { shop, scope, accessToken } = ctx.state.shopify;
  const host = getHost(ctx);
  ACTIVE_SHOPIFY_SHOPS[shop] = scope;
  const returnUrl = `https://${Shopify.Context.HOST_NAME}?host=${host}&shop=${shop}`;
  const subscriptionUrl = await getSubscriptionUrl(accessToken, shop, returnUrl );
  ctx.redirect(subscriptionUrl);
  },
 })
);
```

**Comment by Theantipioneer** [comment]
Did this help anyone? I have the same problem, still.
server.js : from the node tutorial.
`require("isomorphic-fetch");
const dotenv = require("dotenv");
const Koa = require("koa");
const next = require("next");
const { default: createShopifyAuth } = require("@shopify/koa-shopify-auth");
const { verifyRequest } = require("@shopify/koa-shopify-auth");
const { default: Shopify, ApiVersion } = require("@shopify/shopify-api");
const Router = require("koa-router");

dotenv.config();

Shopify.Context.initialize({
    API_KEY: process.env.SHOPIFY_API_KEY,
    API_SECRET_KEY: process.env.SHOPIFY_API_SECRET,
    SCOPES: process.env.SHOPIFY_API_SCOPES.split(","),
    HOST_NAME: process.env.SHOPIFY_APP_URL.replace(/https:\/\//, ""),
    API_VERSION: ApiVersion.April21,
    IS_EMBEDDED_APP: true,
    SESSION_STORAGE: new Shopify.Session.MemorySessionStorage(),
});

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

const ACTIVE_SHOPIFY_SHOPS = {};

app.prepare().then(() => {
    const server = new Koa();
    const router = new Router();
    server.keys = [Shopify.Context.API_SECRET_KEY];

    server.use(
        createShopifyAuth({
            afterAuth(ctx) {
                const { shop, scope } = ctx.state.shopify;
               
                ACTIVE_SHOPIFY_SHOPS[shop] = scope;

                ctx.redirect(`/`);
                ctx.redirect(`/?shop=${shop}`);
            },
        })
    );


    const handleRequest = async (ctx) => {
        await handle(ctx.req, ctx.res);
        ctx.respond = false;
        ctx.res.statusCode = 200;
    };

    router.get("/", async (ctx) => {
        const shop = ctx.query.shop;

        if (ACTIVE_SHOPIFY_SHOPS[shop] === undefined) {
            ctx.redirect(`/auth?shop=${shop}`);
        } else {
            await handleRequest(ctx);
        }
    });

    router.get("(/_next/static/.*)", handleRequest);
    router.get("/_next/webpack-hmr", handleRequest);
    router.get("(.*)", verifyRequest(), handleRequest);

    server.use(router.allowedMethods());
    server.use(router.routes());

    server.listen(port, () => {
        console.log(`> Ready on http://localhost:${port}`);
    });
});
`
.env
`SHOPIFY_API_KEY=0000
SHOPIFY_API_SECRET=0000
SHOPIFY_API_SCOPES=read_products
SHOPIFY_APP_URL=https://daee3b7889af.ngrok.io`

next.config.js
`require("dotenv").config();
const webpack = require("webpack");

const apiKey = JSON.stringify(process.env.SHOPIFY_API_KEY);
const host = JSON.stringify(process.env.SHOPIFY_APP_URL);

module.exports = {
    webpack: (config) => {
        const env = { API_KEY: apiKey, HOST_URL: host };
        config.plugins.push(new webpack.DefinePlugin(env));
        return config;
    },
};
`
app.js
`import App from "next/app";
import Head from "next/head";
import { AppProvider } from "@shopify/polaris";
import { Provider } from "@shopify/app-bridge-react";
import "@shopify/polaris/dist/styles.css";
import translations from "@shopify/polaris/locales/en.json";
import ClientRouter from "../components/ClientRouter";

class MyApp extends App {
    render() {
        const { Component, pageProps, shopOrigin, host } = this.props;
        const config = {
            apiKey: API_KEY,
            shopOrigin,
            host,
            forceRedirect: true,
        };
        return (
            <React.Fragment>
                <Head>
                    <title>Sample App</title>
                    <meta charSet="utf-8" />
                </Head>
                <Provider config={config}>
                    <ClientRouter />
                    <AppProvider i18n={translations}>
                        <Component {...pageProps} />
                    </AppProvider>
                </Provider>
            </React.Fragment>
        );
    }
}
MyApp.getInitialProps = async ({ ctx }) => {
    return {
        shopOrigin: ctx.query.shop, host: ctx.query.host 
    };
};

export default MyApp;`

**Comment by kinngh** [comment]
@lubojanski thanks for reminding that now you don't have to use a separate function to call in on `host` and instead it's directly available. I've updated the code on my template repository available [here](https://github.com/kinngh/shopify-node-mongodb-next-app) or you can directly look at the individual files at [`pages/_app.js`](https://github.com/kinngh/shopify-node-mongodb-next-app/blob/main/pages/_app.js) and [`server.js`](https://github.com/kinngh/shopify-node-mongodb-next-app/blob/main/server.js)

**Comment by joshbedo** [comment]
Anyone figure out a fix for this I'm trying to deploy the app to AWS Cloudfront and this issue keeps popping up

**Comment by rodrigograca31** [comment]
@joshbedo I'd appriciate if you could share any insights you found? seems you were deploying to AWS.... did it work? did you change anything?

**Comment by bbrooklynite** [comment]
Please note there is a bug in some versions of @shopify/app-bridge-react that will cause the "host must be provided error". 

This bug randomly occurred after an "npm update" with no code changes.

app-bridge-react  2.0.24 seems to be the only stable version.

Also see https://community.shopify.com/c/shopify-apis-and-sdks/shopify-app-bridge-react-getting-error-host-not-provided-after/m-p/1579622

**Comment by towfiqi** [comment]
This also happens when the session expires after 24 hours. Had to manually redirect the app to the auth url to reauthenticate the user to fix this issue.
