### ISSUE TITLE
Manually Enable Cookie Popup when server first starts

### ISSUE THREAD

**Issue by eddy-reynoso** [Shopify/shopify-app-template-node#635]
# Issue summary
Hello. Recently submitted an app for review but was denied due to cookies that I was unaware about. I tried creating a new project from the cli to see if the "Enable cookies popup" goes away and it does not. 

## Expected behavior
App should start without Enable cookies popup.

## Actual behavior
Enable cookie popup happens when server is started

## Steps to reproduce the problem

1. Create new Project with Shopify CLI (Shopify Node Create)
2. Run serve (Shopify Node Serve)
3. Open browser console to Application > Cookies
4. Go to apps ngrok url
5. Kill server
6. Run server again
7. Wait until app starts up again and observe UI and console

## Reduced test case
https://user-images.githubusercontent.com/47189260/124006915-cf43eb00-d9a8-11eb-8652-e67e6cefd74e.mov

https://user-images.githubusercontent.com/47189260/124007163-19c56780-d9a9-11eb-9328-54b7e23c7ffa.mov

## Specifications

- Browser: Chrome
- Device: Macbook, iPhone
- Operating System: macOS, iOS

**Comment by redareda9** [comment]
Damn. Spending so much time making a proper bug report in July and seeing no actual answer from Shopify team from July to... October. Sad to see how they don't care about developers anymore.
