### ISSUE TITLE
AppBridgeError APP::ERROR::INVALID_CONFIG: apikey must be provided

### ISSUE THREAD

**Issue by hnakao** [Shopify/shopify-app-template-node#636]
# Issue summary

I am working on a react/node app created with shopify CLI. I have 3 environments, local, staging and production. Local and staging works fine, local use .env file but staging and production use CI/CD enviroments variables. I'm 100 % sure that SHOPIFY_API_KEY have a correct value. next.config.js and _app.js have not been modified, the api key is configured just like this in this repo.

## Expected behavior

After deployment to production environment the app should be installed and works without throw api key undefined error. 

## Actual behavior

the app is installed but show in browser console a infinite loop showing the error: "AppBridgeError APP::ERROR::INVALID_CONFIG: apikey must be provided"

![image (4)](https://user-images.githubusercontent.com/34839422/124048860-3f706200-d9e5-11eb-8179-950203437457.png)

## Steps to reproduce the problem
next.config.js

```
const { parsed: localEnv } = require('dotenv').config();

const webpack = require('webpack');

const apiKey = JSON.stringify(process.env.SHOPIFY_API_KEY);

module.exports = {
  webpack: (config, { isServer }) => {
    const env = { API_KEY: apiKey };
    config.plugins.push(new webpack.DefinePlugin(env));

    // Add ESM support for .mjs files in webpack 4
    config.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules/,
      type: 'javascript/auto',
    });

    if (!isServer) {
      config.node = {
        fs: 'empty',
      };
    }

    return config;
  },
};
```

_app.js

```
// imports

function userLoggedInFetch(app) {
  const fetchFunction = authenticatedFetch(app);

  return async (uri, options) => {
    const response = await fetchFunction(uri, options);

    if (
      response.headers.get('X-Shopify-API-Request-Failure-Reauthorize') === '1'
    ) {
      const authUrlHeader = response.headers.get(
        'X-Shopify-API-Request-Failure-Reauthorize-Url',
      );

      const redirect = Redirect.create(app);
      redirect.dispatch(Redirect.Action.APP, authUrlHeader || '/auth');
      return null;
    }

    return response;
  };
}

function MyProvider(props) {
  const app = useAppBridge();

  const client = new ApolloClient({
    link: new createHttpLink({
      credentials: 'include',
      fetch: userLoggedInFetch(app),
    }),
    cache: new InMemoryCache(),
  });

  const { Component } = props;

  return (
    <ApolloProvider client={client}>
      <Component {...props} />
    </ApolloProvider>
  );
}

class MyApp extends App {
  render() {
    const {
      Component, pageProps, shopOrigin, accessToken,
    } = this.props;

    return (
      <AppProvider i18n={translations}>
        <Provider
          config={{
            apiKey: API_KEY,
            shopOrigin,
            forceRedirect: true,
          }}
        >
          <RoutePropagator />
          <RestApiContext.Provider value={{ shopOrigin, accessToken }}>
            <AuthProvider>
              <UserProvider>
                <ProductProvider>
                  <MyProvider Component={Component} {...pageProps} />
                </ProductProvider>
              </UserProvider>
            </AuthProvider>
          </RestApiContext.Provider>
        </Provider>
      </AppProvider>
    );
  }
}

MyApp.getInitialProps = async ({ ctx }) => ({
  shopOrigin: ctx.query.shop,
});

export default MyApp;
```

## Specifications

- Browser: Chrome 89.0.4389.114
- Device: Laptop MSI GL62M 7RE
- Operating System: Linux (64-bit) (Ubuntu 20.04)
- Node: v15.14.0.

**Comment by muhammednasimda** [comment]
@hnakao 
Hi have you solved this issue, I am stuck with this issue

**Comment by hnakao** [comment]
Hello @nasimnow,
Sorry for replying so late, hope you have solved the problem. If you haven't, maybe this can help you.
https://shopify.dev/apps/tools/app-bridge/migrating

**Comment by operations-stickyio** [comment]
Hello @hnakao we are facing the same issue. Explanation of why this is happening can be found here https://github.com/Shopify/shopify-cli/issues/516

**Comment by gfolga** [comment]
Hello @nasimnow we are facing the same issue. Explanation of why this happens, can be found in this post https://github.com/Shopify/shopify-cli/issues/516
