### ISSUE TITLE
Retrieving Online and Offline access tokens

### ISSUE THREAD

**Issue by chelovekgenek** [Shopify/shopify-app-template-node#637]
# Issue summary

Hi. The current situation on the project with clients forced to migrate from cookie-based auth model to cookieless. 
For project needs, I need to have an offline token for some background work. But I found that graphql proxy and sessions are supporting the only online type of access mode. So I have to get both types of authentication in Shopify auth flow.

## Expected behavior

It should go through all steps, get both tokens and render the app.

## Actual behavior

Experiencing different types of problems: enable cookies notification bar, auth loop, stuck at getting an online token, graphql proxy doesn't get auth token and throwing an error.
The stacking issue is shown here: https://www.loom.com/share/fc4a551b78c648b3bee13280f9a2d5ae

## Steps to reproduce the problem

https://github.com/chelovekgenek/webapp-auth-example

## Specifications

- Browser: Chrome 91.0.4472.114
- Device: PC
- Operating System: Windows 10, app is running under WSL

**Comment by pravin-logicap** [comment]
Hi @chelovekgenek 
How you have achieved it ? 
I am giving `accessMode:offline` but then it loop me into same auth.

I tried both online and offline, but still it loop me into offline token again and again.

Any update on this ?
