### ISSUE TITLE
Production deployment with nextjs Dockerfile

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [Shopify/shopify-app-template-node#648]
# Issue summary

I'm trying to deploy my app created using this template to a k8s cluster using nextjs docker file here https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile however i'm getting this error `API key must be provided` I have checked the pod and it's running correctly..

<img width="410" alt="Screen Shot 2021-08-09 at 1 30 22 AM" src="https://user-images.githubusercontent.com/36244069/128742698-378a42a7-8ebc-4ebc-b79f-80850d41ed65.png">

**Comment by rodrigograca31** [comment]
Maybe this was solved but Id like to noticed:

1. Your `.env` file should have `SHOPIFY_API_KEY=........`
2. Your `server.js`: `Shopify.Context.initialize({
	API_KEY: process.env.SHOPIFY_API_KEY, ........`
3. Your `_app.js`: `config={{
						apiKey: API_KEY, .......`
4. your `next.config.js`:
```
const { parsed: localEnv } = require("dotenv").config();

const webpack = require("webpack");
const apiKey = JSON.stringify(process.env.SHOPIFY_API_KEY);

module.exports = {
	webpack: (config) => {
		const env = { API_KEY: apiKey };
		config.plugins.push(new webpack.DefinePlugin(env));

		// Add ESM support for .mjs files in webpack 4
		config.module.rules.push({
			test: /\.mjs$/,
			include: /node_modules/,
			type: "javascript/auto",
		});

		return config;
	},
};
```

**Comment by rodrigograca31** [comment]
But!
I was unable to deploy anywhere else other than Heroku....

**Comment by mkamalkayani** [comment]
I also faced this issue while deploying the nextjs app to a k8 cluster. The problem was that the API_KEY was not getting injected into the docker image during the build phase and thus not available to nextjs build.

So, I added the Api key to the docker image with

```
docker build --build-arg NEXT_PUBLIC_SHOPIFY_API_KEY=<api-key>
```

and then used it in the nextjs build using the docker `ARG`
```
ARG NEXT_PUBLIC_SHOPIFY_API_KEY

RUN npm run build 
```
