### ISSUE TITLE
Impossible to add url which does not require createShopifyAuth

### ISSUE THREAD

**Issue by wellbranding** [Shopify/shopify-app-template-node#679]
The embedded app works well, but we need to add the route, which does not require createShopifyAuth middleware. The problem is that we tried to use koa-compose to compose our middleware, but it is still impossible to omit the createShopifyAuth middleware. Provide the code example, on how can you create a page, which points to /public-endpoint URL and does not **require the createShopifyAuth**, so that you can easily access this page, without installing it as the Shopify app.

**Comment by lh15** [comment]
Did you find a solution for this?
