### ISSUE TITLE
405 Error when form submit POST

### ISSUE THREAD

**Issue by PurplePineapple123** [Shopify/shopify-app-template-node#686]
I'm trying to submit a form but get a 405 error when trying to POST to my api route. I've tried using both axios and the fetch api. 

## What do you think should happen?

Expect this object to be returned: ```{ name: 'Success' }``` - Successful POST request

## What actually happens?

405 Error: https://snipboard.io/u8PKS6.jpg

## Steps to reproduce the problem

Scaffold with Shopify CLI. Create an api endpoint and a page to call that endpoint from. 

**/survey/create**
```
const handleSubmit = async (event) => {
    event.preventDefault();

    const testData = {
      title: surveyTitle,
    };

    const res = await fetch("/api/survey", {
      method: "POST",
      body: JSON.stringify({
        dataName: testData,
      }),
      headers: {
        "Content-Type": "application/json",
      },
    });
  };

```
**/api/survey**
```
export default function handler(req, res) {
  console.log(req.body);
  res.status(200).json(JSON.stringify({ name: 'Success' }))
}
```

## Specifications

- Browser: Chrome 96
- Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
- Operating System: MacOS Catalina

**Comment by FelixBehr** [comment]
simple fix allthough you need to handle security yourself than.

add 

```js
  router.all("/api/(.*)", handleRequest); // api is clear as well
```

before
```js
  router.get("/_next/webpack-hmr", handleRequest); // Webpack content is clear
  router.get("(.*)", async (ctx) => {
```

in server/server.js such that the result looks like this

```js
  router.all("/api/(.*)", handleRequest); // api is clear as well
  router.get("/_next/webpack-hmr", handleRequest); // Webpack content is clear
  router.get("(.*)", async (ctx) => {
```
