### ISSUE TITLE
Typescript??

### ISSUE THREAD

**Issue by j-d-carmichael** [Shopify/shopify-app-template-node#690]
# Issue summary

The full codebase is JS not TS.. where as clearly the shopify team writes in modern typescript  https://github.com/Shopify/shopify-node-api

## Expected behavior

To see typescript

## Actual behavior

See javascript

**Comment by lukeclifton** [comment]
I would be interested to know if typescript for this repo is in the pipeline?

Would it make sense to use something like [NestJS](https://nestjs.com) for the server and continue to use NextJS for the client?

Anyone else be interested in this?

**Comment by nikolan** [comment]
I have only just started build an app and it is extremely frustrating to use the node app from the cli. It seems to have been hacked together to run in development as a learning material rather than a foundation for producing a production app. 
How do people here build the server after converting to typescript, I'm really struggling with unpicking the babel-preset and the server/index.js ?

**Comment by nikolan** [comment]
Thanks, @lukeclifton! Do you call `"build:server"` separately from your build pipeline or is it perhaps a naming convention to integrate with the rest of the build? 
What do you deploy in? I'm using docker and the final image is about 104MB when pushed in the registry. 
I thought of trying some bundeling with esbuild. I don't have much experience running nodejs in production, so filtering noise from signal is still difficult. Thus I found out that the server/index.js should not be run in production. 
Does anyone have any advice on how to build the server with esbuild or perhaps webpack?

**Comment by jono-allen** [comment]
I got a fork of this working with next.js and typescript
You can find it here https://github.com/solvedata/shopify-app-nextjs-typescript

**Comment by nikolan** [comment]
Thanks @jono-allen, this looks great. I appreciate the feedback on the auth. It is a shame they haven't at least documented it.

**Comment by jono-allen** [comment]
@j-d-carmichael thanks for pointing that out, our plan was to start building our app out but good now we know we need another starter project before then. 
Very disappointing the readme hasn't been updated to reflect this on the cli.

I found this repo on the shopify-node-api repo https://github.com/redochka/nextjs-shopify-app-no-custom-server

I'm going to try that and then might convert it to typescript and go from there

**Comment by lukeclifton** [comment]
@jono-allen This repo looks great. Thanks for sharing. 

I have actually been working on a project which uses a similar approach using NextJS and going serverless on Vercel. 
Seems to work really well and for most simple apps should make a great commercial choice.

**Comment by nikolan** [comment]
> 
@lukeclifton did you get it to generate both online and offline tokens? I am thinking to retrofit a shopify cli generated app to this approach.

**Comment by nikolan** [comment]
Looks like Shopify are pivoting towards Express. 

`npx degit shopify/shopify-app-node#sample_app_updates`

I started building our app with their early release of the example app. It has been an upward struggle for me to convert it to Typescript.

**Comment by lukeclifton** [comment]
@nikolan Thanks. Hadn't noticed the update until seeing your message.

**Comment by lukeclifton** [comment]
I can help convert to typescript once its stabilised

**Comment by nikolan** [comment]
Has anyone managed to get their latest node-app running with TS?

**Comment by nikolan** [comment]
This is the closest thing I found to a working example. Hats off to @LeonelAimar for building it. 
https://github.com/LeonelAimar/new-shopify-node-ts-app-boilerplate/blob/master/src/server/middlewares/authHandlers.ts

I had to go get acquainted with esm modules (Node.js TS is my second language). So in the end this is what my scripts look like:
`  "scripts": {
    "build": "npx tsc && yarn run build:client",
    "build:client": "vite build --outDir dist/client",
    "debug": "node --inspect-brk server/index.js",
    "newDev": "cross-env NODE_ENV=development nodemon",
    "dev": "tsc && cross-env NODE_ENV=development nodemon --experimental-specifier-resolution=node dist/server/index.js --watch ./src/**/*",
    "prepare": "husky install",
    "serve": "node --experimental-specifier-resolution=node dist/server/index.js",
    "start": "yarn run serve",
    "test": "vitest --reporter=verbose"
  },`

**Comment by nikolan** [comment]
@LeonelAimar I found the whole setup useful, I meant to link the repo but seem to have copied a link to a particular file. I've edited the original comment with the correct link now. Thanks again for putting it out there and I hope you get the time you need to keep it up as I am sure other people will be flocking to it for the TS goodness.

**Comment by kanzitelli** [comment]
Hey guys! I've come up with this setup https://github.com/kanzitelli/shopify-app-template-typescript. Fully bootstrapped from their template and just wrapped with TS configuration (not an expert tho). I've been testing on my machine with `dev` and `prod` environments, and it seems to be working well. Would be great if you could test it on your side too :)

**Comment by nikolan** [comment]
@kanzitelli that's pretty neat. I like that you are talking about production setup in your README. Running apps in production and building resilient apps are topics I find seriously lacking in any Shopify documentation aimed at onboarding new developers.

**Comment by stevepsharpe** [comment]
> I got a fork of this working with next.js and typescript You can find it here https://github.com/solvedata/shopify-app-nextjs-typescript

Do you still have a working version of this? I think I'd rather use Next

**Comment by KaiSpencer** [comment]
Ive started a port of the CLI generated app to typescript.
Frontend is done and most of the express backend is done.

Feel free to use this to get started :)
https://github.com/KaiSpencer/shopify-app-template-node-ts

**Comment by knsakib** [comment]
> Ive started a port of the CLI generated app to typescript. Frontend is done and most of the express backend is done.
> 
> Feel free to use this to get started :) https://github.com/KaiSpencer/shopify-app-template-node-ts

is it completed?

**Comment by knsakib** [comment]
> Hey guys! I've come up with this setup https://github.com/kanzitelli/shopify-app-template-typescript. Fully bootstrapped from their template and just wrapped with TS configuration (not an expert tho). I've been testing on my machine with `dev` and `prod` environments, and it seems to be working well. Would be great if you could test it on your side too :)

Are you able to convert the boilerplate of Shopify cli@3.x?

**Comment by cyrilchapon** [comment]
@kanzitelli , I'm highly interested on collaborating on your template as it's the closest working thing I've seen so far. How can I reach you ?

**Comment by cyrilchapon** [comment]
@knsakib my bad bro, I made a mistake, was talking about @KaiSpencer repository. His one is using shopify/cli v3 which is much closer of current version of this repo.

**Comment by tomotomy** [comment]
I converted Template that made with Shopify CLI 3.x to Typescript.
Please try it if you have some problems.
https://github.com/tomotomy/shopify-app-template-node-typescript

**Comment by knsakib** [comment]
> I converted Template that made with Shopify CLI 3.x to Typescript. Please try it if you have some problems. https://github.com/tomotomy/shopify-app-template-node-typescript

Amazing!! It is working!! respect!! 🙏🙏

**Comment by blanklob** [comment]
Thanks bro @tomotomy I added it to my Discord.

**Comment by tomotomy** [comment]
@blanklob 
Thanks! I'll check your Discord server 👋

**Comment by cyrilchapon** [comment]
@tomotomy with @KaiSpencer we continued the work over there on his repo : https://github.com/KaiSpencer/shopify-app-template-node-ts

why not joining forces over there ? I can make a diff once maybe, check differences between repos and keep the best of each. There are basically the same, (cli 3 was already implemented there)

**Comment by tomotomy** [comment]
@cyrilchapon 
Thank you for sharing. I'll check the repo!

**Comment by SaeedYasin** [comment]
Here is an updated template with Typescript and Prisma etc. https://github.com/SaeedYasin/shopify-app-template-node

**Comment by blanklob** [comment]
Is your template still updated with Shopify current JS alternative? @SaeedYasin

**Comment by blanklob** [comment]
Thanks I will use it 💚

**Comment by lukeclifton** [comment]
So I come back to this thread and still wonder if adding a Typescript option to the official node app repo is part of the roadmap or not? 

@paulomarg @mkevinosullivan Can you shed any light on this?

When using the Shopify 3.0 CLI for apps and generating an extension you get the option to roll Javascript OR Typescript.
Something similar for this app boilerplate seems like what should exist?

**Comment by mkevinosullivan** [comment]
@lukeclifton Writing this template in JavaScript was an intentional decision when it was first created in order to support novice developers who were also going through the tutorials on https://shopify.dev.

As of now, converting the current app template to TypeScript is not on the roadmap, and not likely to be revisited anytime soon given the staff reductions last week.

**Comment by cyrilchapon** [comment]
Commenting because.
This shouldn't be closed as of 2023 basically there is no decent reason not to use Typescript.

This app template should be rewriten.

**Comment by rajdeepkhandelwal** [comment]
Yes agree.

**Comment by pyyding** [comment]
@maruffahmed  just rename .js -> .ts 😄
