### ISSUE TITLE
Are there plans for an update?

### ISSUE THREAD

**Issue by jsullivan5** [Shopify/shopify-app-template-node#701]
# Issue summary

I'm reading issues across here and in the supporting libraries that people's apps are being denied due to an old shopify api version used in koa-shopify-auth.  It also seems like after the move to session tokens a lot of this scaffolding is no longer needed.

Is there an update coming here?

This has been super helpful to get started quickly but it seems like this won't pass listing approval unless we use community forked and updated core packages or do something else entirely at the moment.

There are alternatives and fixes out there but having something with Shopify support would be awesome.

## Expected behavior

Apps built with this should be eligible for App Store listing

## Actual behavior

Apps are being denied due to an old API version built into koa-shopify-auth.

**Comment by Michael-Gibbons** [comment]
@jsullivan5 if you're new to the ecosystem the boilerplate is still very good to get up and running. At this moment if you're around senior level it might be more prudent to make your own boilerplate until the express version is released. The main linchpins right now are nextjs, koa, and apollo. NextJS is frankly not required and overcomplicates things, koa isn't as supported as express, and the apollo packages need to be updated to use `@apollo/client`. So if you can avoid those packages you should jump the main hurdles in this boilerplate.
