### ISSUE TITLE
GDPR Webhook Integration

### ISSUE THREAD

**Issue by akeans-mgs** [Shopify/shopify-app-template-node#741]
Our app was rejected by Shopify's automated submission test immediately after submission with the same reason of

> App must verify the authenticity of the request from Shopify.
> Expected HTTP 401 (Unauthorized), but got HTTP 405 from https://8235cf20c428.ngrok.io/webhook/gdpr/shop_redact. Your app's HTTPS webhook endpoints must validate the HMAC digest of each request, and return an HTTP 401 (Unauthorized) response when rejecting a request that has an invalid digest.

Error I received

```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined in
at Hmac.update (internal/crypto/hash.js:84:11)
at receiveWebhookMiddleware( \node_modules@shopify\koa-shopify-webhooks\build\cjs\receive.js:32:63 )
at dispatch( \node_modules@shopify\koa-shopify-webhooks\node_modules\koa-compose\index.js:42:32 )
at bodyParser \node_modules\koa-bodyparser\index.js:95:11)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at \node_modules\koa-mount\index.js:58:5
```

You can check the code here.
https://github.com/akeans-mgs/mgs_testing

**Comment by Michael-Gibbons** [comment]
I believe this is a question more geared towards the node api package, here is a similar issue 

https://github.com/Shopify/shopify-node-api/issues/256

Hope some info in there helps

**Comment by unlocomqx** [comment]
Here's simple code sample
```ts
Shopify.Webhooks.Registry.addHandlers({
  "CUSTOMERS_DATA_REQUEST": {
    path: "/webhooks",
    webhookHandler: processCustomersDataRequest,
  },
  "CUSTOMERS_REDACT": {
    path: "/webhooks",
    webhookHandler: processCustomersRedact,
  },
  "SHOP_REDACT": {
    path: "/webhooks",
    webhookHandler: processShopRedact,
  },
})

// json examples here https://shopify.dev/apps/webhooks/configuration/mandatory-webhooks

export async function processCustomersDataRequest(topic: string, shop: string, body: string) {
  try {
    const {
      shop_domain,
      customer: {
        id,
        email,
      },
      orders_requested,
    } = JSON.parse(body)
    // log event or send an email notification
  } catch (e) {
    console.error(e)
  }
}

export async function processCustomersRedact(topic: string, shop: string, body: string) {
  try {
    const {
      shop_domain,
      customer: {
        id,
        email,
      },
      orders_to_redact,
    } = JSON.parse(body)
    // log event or send an email notification
  } catch (e) {
    console.error(e)
  }
}

export async function processShopRedact(topic: string, shop: string, body: string) {
  try {
    const { shop_domain } = JSON.parse(body)
    // log event or send an email notification
  } catch (e) {
    console.error(e)
  }
}

// this block of code is already present in the starter app
app.post("/webhooks", async (req, res) => {
  try {
    await Shopify.Webhooks.Registry.process(req, res);
    console.log(`Webhook processed, returned status code 200`);
  } catch (error) {
    console.log(`Failed to process webhook: ${error}`);
    res.status(401).send(error.message);
  }
});
```

**Comment by Michael-Gibbons** [comment]
Thanks @unlocomqx ! perfect

**Comment by prathamesh86A** [comment]
> ```ts
> Shopify.Webhooks.Registry.addHandlers({
>   "CUSTOMERS_DATA_REQUEST": {
>     path: "/webhooks",
>     webhookHandler: processCustomersDataRequest,
>   },
>   "CUSTOMERS_REDACT": {
>     path: "/webhooks",
>     webhookHandler: processCustomersRedact,
>   },
>   "SHOP_REDACT": {
>     path: "/webhooks",
>     webhookHandler: processShopRedact,
>   },
> })
> ```

do we have to do HMAC validation in same or there is no need of that ?

**Comment by unlocomqx** [comment]
I don't remember the code very well but I think that `Shopify.Webhooks.Registry.process` takes care of everything for you. Check the source code to be sure.

Just give it the same endpoint, which is `/webhooks`, You don't need different endpoints in this example.

**Comment by prathamesh86A** [comment]
@unlocomqx and about the testing part do u have any idea how can i test it as i tested earlier but didnt got anything on my console there....
should i try submitting my app directly or it must be tested ?

**Comment by unlocomqx** [comment]
@prathamesh86A I tested it using [RapidAPI](https://paw.cloud/). You need to pass in the access_token or whatever (sry I forgot about it)
