### ISSUE TITLE
Recurring Billing on App Installation

### ISSUE THREAD

**Issue by d-motzer** [Shopify/shopify-app-template-node#791]
I'm having an issue with showing the subscription agreement page after auth.

In my auth.js, this is my /auth/callback logic with the GQL query for appSubscriptionCreate:

`

    app.get("/auth/callback", async (req, res) => {
        try {
            const session = await Shopify.Auth.validateAuthCallback(
                req,
                res,
                req.query
            );
            console.log("validating auth ");

            const host = req.query.host;
            app.set(
                "active-shopify-shops",
                Object.assign(app.get("active-shopify-shops"), {
                    [session.shop]: session.scope,
                })
            );

            const response = await Shopify.Webhooks.Registry.register({
                shop: session.shop,
                accessToken: session.accessToken,
                topic: "APP_UNINSTALLED",
                path: "/webhooks",
            });

            if (!response["APP_UNINSTALLED"].success) {
                console.log(
                    `Failed to register APP_UNINSTALLED webhook: ${response.result}`
                );
            }

           

            // Redirect to app with shop parameter upon auth

            const returnUrl = `/?shop=${session.shop}&host=${host}`
            const subscriptionQuery = `mutation {
      appSubscriptionCreate(
          name: "A test recurring plan"
          returnUrl: "${returnUrl}"
          test: true
          lineItems: [
          {
            plan: {
              appRecurringPricingDetails: {
                  price: { amount: 69.99, currencyCode: USD }
              }
            }
          }
          ]
        ) {
            userErrors {
              field
              message
            }
            confirmationUrl
            appSubscription {
              id
            }
        }
    }`
            const client = new Shopify.Clients.Graphql(
                session.shop,
                session.accessToken
            );
            await client.query({ data: subscriptionQuery });

            res.redirect(`/?shop=${session.shop}&host=${host}`);
        } catch (e) {
            switch (true) {
                case e instanceof Shopify.Errors.InvalidOAuthError:
                    res.status(400);
                    res.send(e.message);
                    break;
                case e instanceof Shopify.Errors.CookieNotFound:
                case e instanceof Shopify.Errors.SessionNotFound:
                    // This is likely because the OAuth session cookie expired before the merchant approved the request
                    res.redirect(`/auth?shop=${req.query.shop}`);
                    break;
                default:
                    res.status(500);
                    res.send(e.message);
                    break;
            }
        }
    });

`

However, all it's doing is installing the app without prompting for agreement to the recurring charge. Any one else having this as well?

**Comment by elachino** [comment]
You got error on returnUrl, you have to use a absolute url and not relative url:

`const returnUrl = /?shop=${session.shop}&host=${host}` -> `const returnUrl =https://xxxx.com/?shop=${session.shop}&host=${host}`

You have to redirect to confirmationUrl and not to default redirect:
 
```  
const respGL = await client.query({ data: subscriptionQuery });
const confirmUrl = respGL.body.data.appSubscriptionCreate.confirmationUrl;
res.redirect(confirmUrl); 
```
