### ISSUE TITLE
ClientRouter and RoutePropagator components is not working on the new vite.js shopify react app.

### ISSUE THREAD

**Issue by shafiimam** [Shopify/shopify-app-template-node#792]
Hi devs. The new vite.js react app is not working with the existing app bridges ClientRouter and RoutePropagator components. 
Is there  any new approach to keep the window url synced with  routing inside the embedded app?I am using the react-router-v6.

**Comment by dan-gamble** [comment]
Check [this branch](https://github.com/Shopify/shopify-app-node/tree/multi_page_fe_template)
