### ISSUE TITLE
shopify app serve not work

### ISSUE THREAD

**Issue by qiaodawang** [Shopify/shopify-app-template-node#824]
# Issue summary
After following the Shopify 'create an app' steps and using the CLI to clone the shopify node app, I have been unable to run the shopify app serve command 

Node version: 17.3.0
NPM version: 8.5.5

## Actual behavior

![Lark20220517-233202](https://user-images.githubusercontent.com/102281983/168850343-83fc21a6-7c04-47e1-81e2-9bc29c78bfed.png)

**Comment by dani-sanomads** [comment]
Hi,
Kindly check the App urls in the App Setup from Partner Dashboard.
Right now the ngrok is showing a url with '/login' instead of '/auth'.
Link => https://[ngrok-link]/login/[your-store]
