### ISSUE TITLE
Type 'ParsedQs' cannot be used as an index type.

### ISSUE THREAD

**Issue by remyoswalt** [Shopify/shopify-app-template-node#896]
# Issue summary

![image](https://user-images.githubusercontent.com/92564290/174586972-5625bd78-0eb7-4aa7-8568-62cc22ccea3e.png)

I am getting an error in the index.js file, I am not sure why getting this error

## Expected behavior

I just install the embedded app code from Shopify cli, but its throwing this error in index.js

![image](https://user-images.githubusercontent.com/92564290/174587246-bbadd982-0d9b-4d21-a742-23335aa8fe45.png)

## Specifications

- Browser: brave
- Device:
- Operating System: Windows 10

**Comment by kanzitelli** [comment]
Hey @remyoswalt! I've faced the same issue, however the error is coming for `js` files from `ts` setup which is weird. The workaround with `js` files for this is to wrap `shop` with `String(shop)` and `req.query` with `JSON.parse(JSON.stringify(req.query))`.

If you'd like to try the same template with TS setup, you can checkout [shopify-app-template-typescript](https://github.com/kanzitelli/shopify-app-template-typescript) that I maintain and this error is avoided more in TS way -- https://github.com/kanzitelli/shopify-app-template-typescript/blob/main/server/index.ts#L98

**Comment by remyoswalt** [comment]
@[kanzitelli](https://github.com/kanzitelli), Thank you so much for helping, is there not any way to solve this error within js files? I am not that much familiar with typescript and personally want to use javascript for the whole project.
