### ISSUE TITLE
Where to add read_all_orders,read_orders,write_orders Scope in New Node App

### ISSUE THREAD

**Issue by mveer08** [Shopify/shopify-app-template-node#969]
Where to add read_all_orders,read_orders,write_orders Scope in New Node App

In previous app, we had environment file to add scope. Now new Node app doesnt have environment file.

**Comment by dan-gamble** [comment]
[You can still use an environment variable called `SCOPES`](https://github.com/Shopify/shopify-app-template-node/blob/main/server/index.js#L20)

**Comment by stephenkeable** [comment]
With CLI 3.0 you can also set it in the `shopify.app.toml` file in the scopes variable.
https://github.com/Shopify/shopify-app-template-node/blob/cli_three/shopify.app.toml

**Comment by SameerKShine** [comment]
i added scopes in shopify.app.toml and console the scopes in index.js and it didnt updates the scopes only shows 'write_products'

**Comment by AhsanBetalogics** [comment]
> i added scopes in shopify.app.toml and console the scopes in index.js and it didnt updates the scopes only shows 'write_products'

did you get answer of this?
