### ISSUE TITLE
Problem with npm run serve, unable to access static files in dist/client/assets

### ISSUE THREAD

**Issue by luke-ichpekov** [Shopify/shopify-app-template-node#986]
Using this template and running npm run serve, OAUTH is working fine, but when I load into app it's just an empty page and I get the following error. It looks like my index.html is unable to locate my static files in dist/client/assets. Could be an error in express serving static files, but I'm using the default server from template, and it seems to locate my index.html file fine.

![image](https://user-images.githubusercontent.com/50455100/182662280-23730759-c5da-450a-98ea-e9bfc8682d6b.png)
![image](https://user-images.githubusercontent.com/50455100/182662776-50f8e8c5-6512-448d-a3bf-9f4f00b5e1e7.png)
![image](https://user-images.githubusercontent.com/50455100/182662828-18d53dfc-a3f0-406f-b618-82ad677de4a5.png)
![image](https://user-images.githubusercontent.com/50455100/182662901-8628dfa6-9c5b-43a5-8f83-e6fc4caf0f0c.png)

**Comment by StefanoDiLegami** [comment]
@luke-ichpekov Hey, how could you fix this?

**Comment by StefanoDiLegami** [comment]
> ~Hi @luke-ichpekov would you mind sharing the solution?~
> 
> @StefanoDiLegami In production, the `assets/` files can be found at the root of app. So I had to change my path from `/assets/image.png` `/image.png`. Hope this helps!

@devstein It's been some time ago but still thanks for the reply, I found the solution after some debugging also.
