### ISSUE TITLE
I can't see the any  sqlite database into code root dir

### ISSUE THREAD

**Issue by Sky-bits** [Shopify/shopify-app-template-node#993]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?  i can install the app but i can't see the database.sqlite in website root dir. it shoud be

## Actual behavior

What actually happens?
db file not genrated 

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.   shopify app create node
 2.  cd  to app/
 3.  shopify app serve
   you will see the ngrock url to app install it work fine.
4. based on the document   database.sqlite  genreated in website root directory 

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: chrome 
- Device: hp
- Operating System: Ubuntu

**Comment by mkevinosullivan** [comment]
> 1. shopify app create node
> 2. cd to app/
> 3. shopify app serve
> you will see the ngrock url to app install it work fine.
> 4. based on the document database.sqlite genreated in website root directory

Commands 1 and 3 above indicates you're using CLI version 2, which will soon be deprecated
No. 2 indicates the app template used with CLI 2 (branch `cli_two` of this repo)
No. 4 above indicates documentation of template used by CLI 3.

I would suggest to follow tutorial at https://shopify.dev/apps/getting-started/create and use latest CLI (v3) and associated templates.
