### ISSUE TITLE
NPM RUN DEV - tunnel starts running but TIMED OUT ERROR before receiving APP URL

### ISSUE THREAD

**Issue by JKump** [Shopify/shopify-app-template-node#995]
# Issue summary

Please, please help! I have searched for two days now and no one seems to have this issue! 
Having followed the guide to create a new app from Shopify, stuck on the step when running npm run dev, received success message that tunnel is now running, but not receiving any more terminal output but after a few seconds just an ERROR - TIMED OUT output in the terminal. Could not find this error anywhere else. When trying to go the old way by using Shopify app create with Node and then Shopify app serve, it worked and the tunnel was created and I could install the app. Does not work with this new way with the integrated Shopify CLI. 

## Expected behavior

After running npm run dev, I should receive terminal output about the App URL generated by ngrok and when clicking on it to be able to install the app. 

## Actual behavior

after running npm run dev and the success message 
✅ Success! The tunnel is running and you can now view your app. 
after a few seconds just an
━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    timed out

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
output in the terminal. 

## Steps to reproduce the problem

1. 1. 1. Just follow the 'Create an app' tutorial using Node.js (https://shopify.dev/apps/getting-started/create)

## Specifications

- Browser: Chrome 103 (newest version)
- Device: iMac 2020
- Operating System: MacOC Monterey
- Node.js
- Package Manager: npm
- ngrok signed up
- partner account signed up
- dev store signed up
<img width="633" alt="Screenshot 2022-08-06 at 15 07 46" src="https://user-images.githubusercontent.com/66203984/183252606-c185bffd-7898-4881-abd8-c9c157245461.png">

**Comment by RMartires** [comment]
Hey i've been getting some issues due to ngrok timing out as well, 
i found a quick work-around https://github.com/Shopify/shopify-app-template-node/issues/994

**Comment by rahul138** [comment]
i am also facing same issue, update here if someone finds permanent solution
